.sops.yaml

This PR adds an age key for user karim in the `terraform/secrets.yaml` file.

Add age key under terraform/secrets.yaml  for user karim

---

terraform/README.md

Changes to Terraform README based on feedback from @karim20230

Terraform: clarify benefits of remote state

---

terraform/azure-ghaf-infra.tf

-Enhances network security configurations.
-Implements common and specific rules for specified ports.
-Improves infrastructure security posture.

Implements common, specific rules and specified ports

---

hosts/common.nix
terraform/scripts/ubuntu-builder.sh

To be merged when we switch over to the new cache.

Change cache.vedenemo.dev public key to new nixos cache

---

hosts/prbuilder/configuration.nix
users/cazfi.nix

Added screen and docker access right for Marko L

Added screen  and docker access right

---

hosts/ficolobuild/configuration.nix
users/default.nix
users/themisto.nix

Create a builder account for CI which can start builds in builder machines.

Add a builder account for CI

---

hosts/prbuilder/configuration.nix
users/barna.nix
users/default.nix

Add Barna as a user and grant access to the PRbuilder host

Add Barna as a user and grant access to the PRbuilder host

---

hosts/ficolobuild/configuration.nix

add karim to build3

---

users/jrautiola.nix

Adding ssh keys from new laptop and desktop

Add new ssh keys for user jrautiola

---

hosts/prbuilder/configuration.nix
users/default.nix
users/mika.nix

add mika as a user

---

hosts/binarycache/configuration.nix
hosts/default.nix
hosts/ficolo-common.nix
hosts/ficolo-hosts.nix
hosts/ficolobuild/configuration.nix
hosts/monitoring/configuration.nix
hosts/prbuilder/configuration.nix

Also updated copyrights of the relevant files and added ficolo DNS setup also to prbuilder.
Tested on prbuilder.

Use ci-server as DNS instead of /etc/hosts entries

---

hosts/ficolobuild/configuration.nix

adding mika to build3

---

terraform/playground/terraform-playground.sh

Fix terraform palyground WORKSPACE name uppercase characters to lower…

convert any uppercase to lower case

---

hosts/ficolobuild/build3.nix

Adding brian to remote builder build3

Add bmg to build3

---

hosts/ficolobuild/developers.nix

Provide access to remote builder

Pr add milla and samuli to developers

---

terraform/README-azure.md
terraform/README.md
terraform/main.tf
terraform/playground/README.md
terraform/terraform-init.sh

Restructure the documentation under `terraform` directory to provide details for the intended usage.

Restructure terraform documentation

---

hosts/prbuilder/configuration.nix

Fix Nginx import

---

hosts/ficolobuild/developers.nix

@brianmcgillion requested to a new key to be authorized for his account on x86 builder machine.

x86 builder: Add a new SSH key to bgm

---

hosts/azure-common.nix

Initial garbage-collection configuration for azure VMs

azure-common: Initial garbage-collection config

---

terraform/README.md
terraform/binary-cache.tf
terraform/builder.tf
terraform/jenkins-controller.tf
terraform/main.tf
terraform/terraform-init.sh

Support deploying ghaf-infra to other locations in addition to the default (North Europe).
For more details, see the documentation added in this PR: https://github.com/tiiuae/ghaf-infra/blob/b620eb8147fc72df45bd25daff4ee1e8e8189c1e/terraform/README.md#changing-azure-deploy-location

Support deploying to different locations

---

hosts/binarycache/configuration.nix

Add user hrosten to binarycache-ficolo host

binarycache-ficolo: Add user hrosten

---

hosts/ficolobuild/builder.nix

Adding some tools to x86 builders needed by Hydra and easy up administration work there:
- Python 3.10.13 + requests package
- GNU Screen

Add Python and and Screen to x86 builder

---

ssh-keys.yaml
terraform/jenkins-controller.tf

Add mkaapu user with ssh key to Jenkins controller VM to ease up my CI design and development work.

Jenkins controller: Add user mkaapu

---

hosts/binarycache/configuration.nix
hosts/ficolobuild/build3.nix
users/avnik.nix
users/default.nix

Alexander will start investigating Ghaf X1 Carbon build hash mismatch error.
So adding user account for him in build3 x86 builder.

Add user avnik

---

flake.lock
hosts/binarycache/configuration.nix
hosts/common.nix
services/binary-cache/default.nix

nixpkgs updated to avoid the zstd nginx plugin issue.
This is kind of a pre-review as I have not tested the changes yet.
I'd like to have a review from more epxerienced people, before I possibly do something bad on the cache (or other servers).
In any case, rollback should be possible in case of trouble.

Suggested improvements on server configurations, mainly targeting cache, but involve common settings too

---

.sops.yaml
hosts/binarycache/secrets.yaml
hosts/default.nix
hosts/ficolobuild/build3/configuration.nix
hosts/ficolobuild/build3/secrets.yaml
hosts/ficolobuild/build4/configuration.nix
hosts/monitoring/secrets.yaml

Adds secrets capability and awsarm remote builder for build3 machine.

Add awsarm as aarch64 remote builder for build3

---

hosts/testagent/configuration.nix
ssh-keys.yaml
terraform/binary-cache.tf
terraform/jenkins-controller.tf

Add jrautiola user to NixOs testagent configuration.

Add jrautiola user to testagent

---

terraform/binary-cache.tf
terraform/playground/test-infra.tf

Replacing the hardcoded test user configuration with a dynamic generation of user configurations
-Adding users

Improve user configuration in test terraform script and add users 

---

hosts/azure/jenkins-controller/configuration.nix

Required for provenance in jenkins pipeline

Install jq for provenance

---

hosts/azure/jenkins-controller/configuration.nix

csvlook will be used to transform analyze tools .csv files to nicely formatted txt files

Add csvkit for csvlook tool usage

---

hosts/prbuilder/configuration.nix

Fix in himalia ngnix service proxypass

Fix himalia ngnix proxypass

---

hosts/monitoring/configuration.nix

-This update addresses the bug in the Grafana monitoring alerts for our awsarm env
-The bug fix ensures that alerts are now generated correctly, improving system monitoring and reliability.

Bug fix awsarm grafana alert.

---

hosts/builders/build3/configuration.nix
hosts/builders/build4/configuration.nix
hosts/builders/hetzarm/configuration.nix

Adds ability to build 32 bit derivations

Add i686-linux to x86 builders and themisto user to hetzarm

---

hosts/builders/hetzarm/configuration.nix
hosts/monitoring/configuration.nix

-Adding hetzarm to monitoring service to ensure that our monitoring service is tracking the performance and status of hetzarm.
-Adding Sshified which provides secure access and monitoring of the Hetzarm server.

Add hetzarm to monitoring with sshified

---

hosts/testagent/brainstem.nix

It seems 2.10.5 is unable to change the upstream port:
```
AcronameHubCLI -u 1
Sucessfully connected to USBHub3p SN: 0xEE92E4FD
There was an error (2) changing the upstream port
```
Revert to 2.9.25, which doesn't expose this issue.
Unfortunately, upstream doesn't seem to host that version on their website anymore (?), or at least the URL looks different, so use the one we vendored into the `ci-test-automation` repo for now.

hosts/testagent: downgrade brainstem to 2.9.25

---

hosts/testagent/configuration.nix

For the test jobs to know what hardware is connected to this agent

Add hardware test devices configuration file

---

hosts/testagent/configuration.nix
users/default.nix
users/mariia.nix

Adds connection to controller as a systemd service. Adds mariia user to ghaf-infra configuration
and testagent host.

Adds jenkins connection and mariia user

---

hosts/azure/jenkins-controller/configuration.nix
terraform/main.tf

- Jenkins-controller: Add pre-merge Jenkins pipeline, install required Jenkins plugin
- Terraform: beef-up dev instance for pre-merge builds
For more details, see: https://ssrc.atlassian.net/wiki/x/dwB5Qg

Add pre-merge Jenkins pipeline

---

hosts/builders/developers.nix

Update ghaf-infra developers.nix

Update ghaf-infra developers

---

ssh-keys.yaml
terraform/jenkins-controller.tf

Add Kai with ssh access to jenkins-controller VM

Add user ktu to jenkins-controller

---

hosts/testagent/configuration.nix

Change jenkins user in use with jenkins connection in testagent.
Fix for configuration file.

Change jenkins user in use with jenkins

---

slsa/v1.0/L1/buildtype.md

Initial version of the buildtype document

Add SLSA buildtype document

---

hosts/builders/build3/configuration.nix
terraform/main.tf

Encountering sometimes failures on the Hetzner infra, potentially due to exceeding resource limitations (max jobs)! so Considering lowering the max jobs for Hetzner to a sustainable level !

Reduce sustainable level max jobs

---

hosts/builders/developers.nix

Add ssh pubkey for user vunnyso

---

hosts/testagent/configuration.nix

Add hrosten as a user to testagent

testagent: Add user hrosten

---

hosts/azure/jenkins-controller/configuration.nix

Slack plugin needed to slack build results from pipelines

Add Jenkins Slack plugin

---

flake.lock
flake.nix
pkgs/rclone/default.nix
services/binary-cache/default.nix
services/openssh/default.nix

Update flake nixpkgs input to 24.05 and remove now unnecessary patches

NixOS 24.05

---

hosts/testagent/configuration.nix

Adds configurations of devices from legacy system
dev side setup to testagent's test_configuration file

Adds configurations for test devices

---

hosts/azure/jenkins-controller/configuration.nix

Adds Jenkins pipeline to build FMO-OS.

Add FMO OS Main Pipeline

---

hosts/builders/developers.nix

Member of the ssrc engineering team

ssrc-engineering-members

---

users/tervis.nix

Allow tervis to access machines also from his desktop machine.

Add a ssh-key for tervis@tervis-servu

---

hosts/ghaf-log/configuration.nix
hosts/monitoring/configuration.nix

Monitor ghaflogs.vedenemo.dev using ssh

Start monitoring ghaf logging server

---

docs/deploy-rs.md
flake.lock
flake.nix
nix/default.nix
nix/deployments.nix
nix/devshell.nix

Adds deploy-rs deployment tool, and the necessary configuration in `nix/deployments.nix`

Use deploy-rs

---

terraform/README.md

experimental-feature nix-command must be enabled.

README.md: Document nix-command as a requirement

---

flake.lock
flake.nix
hosts/azure/jenkins-controller/configuration.nix

Adds sbomnix and ci-yubi as flake inputs, and their packages into the jenkins service path.

Add sbomnix and ci-yubi into jenkins path

---

hosts/azure/binary-cache/azure-nix-cache-proxy/src/lib.rs

We currently send application/octet-stream as a content-type, but we can use the correct mime types for NAR, NARInfo and nix-cache-info.
Using text/… for NARInfo and nix-cache-info prevents browsers from treating these URLs as a "Download" vs. just showing inline. Nix ignores them.
Nix uses application/x-nix-nar consistently, for compressed and uncompressed files.

azure-nix-cache-proxy: send mime types

---

hosts/azure/jenkins-controller/configuration.nix

Install Jenkins Copy Artifact plugin

jenkins-controller: Install Copy Artifact plugin

---

hosts/testagent/configuration.nix

Fix for testagent NUC serial port configuration
and udev rule for that.

Fix for NUC serial port config

---

.github/workflows/test-ghaf-infra.yml

* **[tj-actions/changed-files](https://github.com/tj-actions/changed-files)** published a new release **[v45.0.2](https://github.com/tj-actions/changed-files/releases/tag/v45.0.2)** on 2024-09-16T15:15:48Z

Update GitHub Actions to Latest Version

---

terraform/main.tf
terraform/persistent/main.tf
terraform/persistent/workspace-specific/main.tf

Fixes: "Error ensuring Resource Providers are registered"
For reference:
https://github.com/hashicorp/terraform-provider-azurerm/issues/24804

terraform: Skip provider registration

---

hosts/testagent-dev/configuration.nix

Add riscv device configuration and
agent service in testagent-dev configuration.nix
Also udev rule for serial connection.

Add riscv to testagent-dev

---

hosts/azure/jenkins-controller/configuration.nix

Adds a for loop to the post-build-hook that retries the upload once in case it errors. This should stop the azure blob 423 locked error from completely failing our builds.
Not properly tested because I can't reproduce the issue in my infra, but the logic works as a standalone shell script.

Retry post-build upload when azure blob is locked

---

hosts/default.nix
hosts/ghaf-proxy/configuration.nix
hosts/ghaf-proxy/disk-config.nix
hosts/ghaf-proxy/secrets.yaml
nix/deployments.nix
tasks.py

Changes
* Configuration for the server
* Disk formatting and mounts
* Include the new server into existing deployment
* Added existing team into server for ssh

Initial host config, nixos setup for ghaf-proxy

---

hosts/testagent-dev/configuration.nix
hosts/testagent/configuration.nix
users/default.nix
users/maarit.nix

Add Maarit user to ghaf-infra users and testagent hosts
Add /dev/disk/by-id/ usb-drive data to devices configuration on testagent-dev
Connect testagent-dev agent services to vjuntunen's Jenkins controller

Add testagent's configuration changes

---

hosts/testagent-dev/configuration.nix

Add testagent-dev agent systemd services for all test targets and device configuration for all targets.
And udev rules.

Add agents services and configurations

---

hosts/azure/jenkins-controller/configuration.nix

- Refactored pipeline creation into a nix function to reduce duplicate code.
- Gave the pipelines more readable names.
- Added parallel hw test as it was missing.

Refactor jenkins job builder configuration

---

hosts/ghaf-proxy/configuration.nix
users/alextserepov.nix
users/default.nix

Add alextserepov to proxy vm

---

hosts/testagent/dev/configuration.nix
hosts/testagent/release/configuration.nix

Add device configurations and udev rules
to testagent-release configuration.nix
Update testagent-dev polarfire's usbsdmux ID

Add device configurations

---

hosts/testagent/agents-common.nix

Add grafana-loki tool to agents

Add grafana-loki tool to agent

---

.sops.yaml
hosts/ghaf-coverity/configuration.nix
hosts/ghaf-coverity/disk-config.nix
hosts/ghaf-coverity/secrets.yaml
nix/deployments.nix
pkgs/coverity/default.nix
tasks.py

* add new host configurations
* package binaries from tii licensed host
* make derivation for build with deps
* bring derivation in pkgs

Recreate ghaf-coverity host

---

flake.lock
flake.nix

Remove now unused flake input `nix-serve-ng`

Remove unused flake input nix-serve-ng

---

hosts/testagent/credentials.yaml

Update testagent plug-pass

---

hosts/testagent/dev/configuration.nix
hosts/testagent/prod/configuration.nix
hosts/testagent/release/configuration.nix

Change usb_sd_mux_port properties to use
devlink property instead of /dev/sgx to make sure
to use right one.

Change usb_sd_mux_port properties

---

README.md
docs/tasks.md

- Update main README.md
- Move tasks.py documentation to its own markdown file

Update main README.md

---

hosts/testagent/agents-common.nix
hosts/testagent/credentials.yaml

For https://github.com/tiiuae/ci-test-automation/pull/170

Add RPi power logger credentials to testagents

---

hosts/testagent/dev/configuration.nix
hosts/testagent/release/configuration.nix

Update testagent's usbsdmux device
configurations.

Update sdmux device config

---

hosts/testagent/release/configuration.nix

Update release testagent polarfire udev rule

Update release polarfire udev rule

---

.sops.yaml
hosts/default.nix
hosts/testagent/uae-dev/configuration.nix
hosts/testagent/uae-dev/disk-config.nix
hosts/testagent/uae-dev/secrets.yaml
nix/deployments.nix
tasks.py

Deploy testagent for dev instance.
Add initial hw targets into configs.
Update nixos-anywhere version in tasks.py to latest release. Fixes upstream [#434](https://github.com/nix-community/nixos-anywhere/pull/434).

Testagent UAE configs

---

hosts/testagent/release/configuration.nix
ssh-keys.yaml
terraform/binary-cache.tf
terraform/jenkins-controller.tf
users/fayad.nix

Update ssh keys with user fayad.

Update fayad keys

---

hosts/testagent/dev/configuration.nix
hosts/testagent/prod/configuration.nix
hosts/testagent/release/configuration.nix

Add configuration properties of relay board
to testagent-dev configuration.

Add relay board properties

---

flake.lock
flake.nix

Reduces total closure size as there are less duplicated dependencies.

Follow more flake inputs

---

hosts/azure/jenkins-controller/configuration.nix

Pipeline itself is being created in https://github.com/tiiuae/ghaf-jenkins-pipeline/pull/128
This PR is about adding it to jenkins controller.

jenkins-controller: Add ghaf-perftest-pipeline

---

hosts/azure/jenkins-controller/plugins.nix

This bumps some of the plugins to their more recent versions.

az-jenkins-controller: bump plugins

---

hosts/monitoring/configuration.nix

Allows Grafana to ping arbitrary URLs, so we can monitor the status of our azure environments without adding extra metrics collectors into the jenkins controller. The metrics collected will be just the status of the http request, but this is enough to send alerts if a resource cannot be reached.

Add blackbox-exporter to monitor azure resources

---

hosts/testagent/agents-common.nix
hosts/testagent/release/configuration.nix

Add relay properties to testagent-release
cofiguration.nix and add python3 and pyserial
to agents-common.nix environment.systemPackages

Add relay properties

---

hosts/azure/jenkins-controller/jenkins-casc.yaml
hosts/testagent/agents-common.nix
hosts/testagent/dev/configuration.nix

Add testagent-dev configuration changes
for that device and agent instance systemd service
Add alextserepov user to testagent-dev

Add Dell7330 agent configuration

---

hosts/azure/jenkins-controller/configuration.nix

Remove FMO OS and ghaf-parallel-hw-test
pipelines

Remove unused pipelines

---

hosts/testagent/dev/configuration.nix
hosts/testagent/prod/configuration.nix
hosts/testagent/release/configuration.nix
users/default.nix
users/mikkos.nix

Sometimes I may need access to testagents.

Add user for Mikko Saarinen

---

hosts/builders/developers.nix

set up Rodrigo for remote builds

devs: Add Rodrigo to the build server users

---

.sops.yaml
terraform/terraform-secrets.yaml

And allow decrypting terraform secrets

Add sops key for ktu

---

hosts/builders/build1/configuration.nix
hosts/builders/build2/configuration.nix
hosts/default.nix
nix/deployments.nix
scripts/nix-fast-build.sh

Add configuration for hosts build1 and build2.
This change is already installed on both hosts.

Add configuration for hosts build1 and build2

---

terraform/main.tf

Downgrade release jenkins controller vm size

---

hosts/ghaf-log/disk-config.nix

This volume is not being used for anything and it's costing us money.

Remove obsolete hetzner volume

---

hosts/azure/jenkins-controller/configuration.nix
hosts/monitoring/configuration.nix
services/openssh/default.nix

Add monitoring service to Azure Jenkins comtrollers (dev, prod and vjuntunen)
and job for that on monitoring server

Add monitoring service to controller

---

hosts/azure/jenkins-controller/jenkins-casc.yaml
hosts/testagent/dev/configuration.nix
hosts/testagent/prod/configuration.nix

Add Oring AGX 64BG to testagents configurations
Add udev rules for both Orin agx per agent
Add own agent and agent service for agx64

Add Orin AGX 64GB

---

hosts/ghaf-auth/configuration.nix

Allows auth requests from uae jenkins controllers.

Auth allow from uae

---

hosts/monitoring/configuration.nix

Also makes prometheus available at https://monitoring.vedenemo.dev/prometheus (with basic auth) for easier debugging

Start monitoring hetz86

---

scripts/nix-fast-build.sh

- Warn if a build produced no output (this happens e.g. when trying to build aarch64 target on x86 remote builder)
- Better describe the '-s' intended usage

nix-fast-build.sh: Warn if no build output

---

hosts/hetzci-dev/configuration.nix
hosts/hetzci-dev/plugins.json
hosts/hetzci-prod/configuration.nix
hosts/hetzci-prod/plugins.json

- Update hetzci-prod/dev jenkins plugins
- Additionally, add dev, prod, and uae-dev testagent users to hetzci-prod/dev

Hetzci update: jenkins plugins

---

hosts/monitoring/configuration.nix

Add proper auth to prometheus dashboard

---

hosts/hetzci/dev/casc/pipelines/modules/utils.groovy
hosts/hetzci/prod/casc/pipelines/modules/utils.groovy
hosts/hetzci/vm/casc/pipelines/modules/utils.groovy

PR https://github.com/tiiuae/ghaf-infra/pull/517 caused regression in the archive step on our Jenkins pipelines.
This commit fixes the regression.

hetzci: Fix regression in Jenkins archival

---

hosts/hetzci/dev/configuration.nix
hosts/hetzci/prod/configuration.nix
hosts/hetzci/vm/configuration.nix

Give `team-testers` an access to hetzci hosts

hetzci: Test team access to hetzci

---

hosts/monitoring/configuration.nix

hosts/monitoring: Stop monitoring Azure Jenkins hosts. Start monitoring `ci-prod.vedenemo.dev` and `ci-dev.vedenemo.dev` instead.

hosts/monitoring: Stop monitoring Azure Jenkins hosts

---

flake.lock
flake.nix
hosts/common.nix

Should fix cases of `error: Nix daemon disconnected unexpectedly (maybe it crashed?)` caused by assertion errors

Use nix 2.30 from unstable

---

hosts/hetzci/prod/disk-config.nix

Expand ci-prod with new volume mount for nix.

Add newly provisioned volume for nix

---

terraform/modules/azurerm-nix-vm-image/main.tf

Correct disk image name after nixpkgs update.

Fix terraform

---

hosts/builders/developers.nix

Add Gayathri to the developers for ghaf QA team

developers: Add Gayathri

---

hosts/hetzci/dev/disk-config.nix

Mounts newly provisioned volume on ci-dev.

Disk configs for new volume on nix store

---

flake.lock

Update sbomnix to include https://github.com/tiiuae/sbomnix/pull/211

Update input: sbomnix

---

flake.lock
hosts/hetzci/dev/casc/pipelines/modules/utils.groovy
hosts/hetzci/jenkins.nix
hosts/hetzci/prod/casc/pipelines/ghaf-nightly.groovy
hosts/hetzci/prod/casc/pipelines/modules/utils.groovy
hosts/hetzci/release/casc/pipelines/modules/utils.groovy
hosts/hetzci/vm/casc/pipelines/ghaf-nightly.groovy
hosts/hetzci/vm/casc/pipelines/modules/utils.groovy

- offline keys created for each build

Add UEFI SecureBoot Signing

---

hosts/ghaf-monitoring/configuration.nix
hosts/ghaf-monitoring/provision/dashboards/relay-status.json

Add relay status dashboard export json
to ghaf-infra and ghaf-monitoring configuration

Add relay status dashboard

---

docs/tasks.md
hosts/hetzci/README.md
nix/checks.nix
nix/devshell.nix
tasks.py

- Automate Hetzner release environment setup with `task.py` task
- Misc cleanup to `task.py`
- Update documentation concerning `task.py` and Hetzner release setup

Automate Hetzner release environment setup

---

hosts/ghaf-monitoring/configuration.nix
hosts/testagent/agent.nix
hosts/testagent/agents-common.nix
nix/packages.nix
pkgs/brainstem/default.nix

No need to `callPackage` in multiple places.

Use packages from self

---

hosts/azure/jenkins-controller/configuration.nix

Add ghaf-release-laptop-pipeline

---

hosts/hetzci/dev/casc/pipelines/modules/utils.groovy
hosts/hetzci/prod/casc/pipelines/modules/utils.groovy
hosts/hetzci/release/casc/pipelines/modules/utils.groovy
hosts/hetzci/vm/casc/pipelines/modules/utils.groovy

There's something strange that occasionally fails in the provenance creation. I'd like to see if running the provenance again on failure makes any difference.

Retry provenance on failure
