tiiuae/ghaf-infra

.github/workflows/test-ghaf-infra.yml, shell.nix, tasks.py
This PR makes the following changes:
- Add github action workflow that runs CI tests against all PRs and merges to main
- Initial CI tests require that `inv pre-push` as well as `terraform fmt` pass
- As soon as `terraform validate` passes, the commented out checks should be also enabled
=>  Add initial CI tests

.github/workflows/test-ghaf-infra.yml, shell.nix, tasks.py, terraform/providers.tf, terraform/variables.tf
- Add terraform fmt check to CI
- Fix current terraform fmt issues
=> Add terraform fmt check to CI

shell.nix, tasks.py
- Introduce 'alias' names for combinations of hostname (IP) and target nixosConfigurations.
- Add task `alias-list` to list all alias names currently configured.
- Change the task.py so that all tasks take the 'alias' name as an argument, instead of separate hostname and configuration name. This makes it less likely to accidentally apply a configuration to a wrong host.
- This also makes it possible to apply tasks to all alias names. As an example, `deploy` without arguments could deploy all specified alias configurations at once. Such changes to tasks will be implemented later in a separate PR.
=> Simplify tasks.py usage

README.md, tasks.py
- Pin nixos-anywhere to prevent possible issues caused by the upstream PR: https://github.com/nix-community/nixos-anywhere/pull/243. Read more from the nixpkgs issue: https://github.com/NixOS/nixpkgs/issues/265014.
- Fix the task.py usage instructions in README.md after https://github.com/tiiuae/ghaf-infra/pull/8.
- Make `nix flake check` pre-push check less verbose.
=> Pin nixos-anywhere, fix README

terraform/azure-ghaf-infra.tf, terraform/outputs.tf, terraform/providers.tf, terraform/variables.tf
- Define Azure Resource Group for Ghaf Hydra Infrastructure
-  Create Virtual Network (VNet) with Address Space 10.0.0.0/16 
- Establish Subnet within the VNet with Address Prefix 10.0.2.0/24 
- Set Up Availability Set for High Availability
- Implement Network Security Group with SSH Access Rule 
- Allocate Public IP for Access
- Implement Network Security Group with SSH Access Rule
- Provision Storage Account for Data Persistence
- Deploy Virtual Machine with Ubuntu 22.04 LTS
=> Create full-func vm

.gitignore, terraform/README.md, terraform/azure-ghaf-infra.tf, terraform/azure-storage/tfstate-storage.tf
- PoC azure arm VM configuration with terraform
- Refactor `azure-ghaf-infra.tf` to sections per VM-specific resources. This is the first step to make it easier to add new VMs.
- Move the terraform resource group location to 'northeurope' due to the needed arm VM resources not being available in 'swedencentral'
- Add `.direnv` directory to `.gitignore`
=> Initial terraform config for azure arm VM

.sops.yaml, hosts/binarycache/default.nix, hosts/binarycache/disk-config.nix, hosts/binarycache/secrets.yaml, hosts/binarycache/secrets.yaml.license, hosts/default.nix, hosts/qemu-common.nix, tasks.py, users/cazfi.nix, users/default.nix, users/hydra.nix, users/jrautiola.nix
Add configuration for nixos binary cache (new cache.vedenemo.dev) that runs in a qemu vm on ficolo. it exposes nix-serve-ng through http (https soon when we get the dns records changed).
includes disko config to format the second disk and mount it under `/nix` to hold the nix store
=> Configuration for binarycache vm

hosts/qemu-common.nix, tasks.py, terraform/README.md, terraform/azure-ghaf-infra.tf, terraform/scripts/ubuntu-builder.sh
- Add a shell script that configures aarch64 ubuntu host so that it can be used part of the buildfarm. Run the script on applying the terraform configuration.
- Start collecting some common terraform errors and solutions to the terraform README.md.
- Apply formatting fixes to qemu-common.nix and tasks.py.
=> Add ubuntu aarch64 builder configuration

hosts/common.nix, hosts/default.nix, hosts/ghafhydra/default.nix, services/hydra/default.nix, tasks.py, terraform/azure-ghaf-infra.tf
Prepare ghaf-infra so that the infra created with terraform can be used with flake nixos configurations. This includes the following changes:
- Remove testhost terraform configuration since it's not used in ghaf-infra.
- Use static internal IP addresses in terraform VM configurations.
- Configure public cloudapp.azure.com domain names for terraform VMs by using the 'domain_name_label' configuration option.
- Use the cloudapp.azure.com domain names in task.py alias hostnames where appropriate.
- Use the azarm VM as a remote aarch64 builder for the ghafhydra (in addition to awsarm).
In addition, this commit changes some common garbage collection options.
=> Start using terraform infra with nixos configs

tasks.py, terraform/scripts/add-remote-user.sh
- On install task, warn if the remote user on the target host is not the current local user. The intention of this check is to make sure the user is aware that their remote login user is not the current local user, which usually means the nixos-anywhere login after installation will fail.
- Provide a helper script `add-remote-user.sh` to make it easy to add the current local user as a remote user on the target host.
=> Check remote user on install task

hosts/binarycache/default.nix
Now we can use acme to get https certificates for the cache domain.
=> Enable https on new cache

hosts/binarycache/secrets.yaml
You can't see the contents but I updated the key names to be `cache.vedenemo.dev:xxx` instead of `binarycache:xxx`
=> Update cache secret keys

scripts/add-remote-user.sh, services/hydra/default.nix, tasks.py, terraform/azure-ghaf-infra.tf
- Increase ghafhydra-dev vm from 'Standard_B8ms' to 'Standard_B16ms'. See azure B-size specifications at: https://learn.microsoft.com/azure/virtual-machines/sizes-b-series-burstable
- Increase ghafhydra-dev disk size to 1TB
- Move the 'add-remote-user.sh' script to repository root under `scripts/` directory, since it just doesn't belong under `terraform/`
- Update azarm public key after re-installing the server. Azarm server private key should really be installed with terraform, but this part is left for another PR later.
=> Beef-up ghafhydra-dev virtual machine

.sops.yaml, hosts/binarycache/default.nix, hosts/default.nix, hosts/monitoring/default.nix, hosts/monitoring/disk-config.nix, hosts/monitoring/secrets.yaml, hosts/monitoring/secrets.yaml.license, hosts/qemu-common.nix, services/default.nix, services/node-exporter/default.nix, tasks.py
Adds monitoring VM running Grafana and Prometheus, that monitors build4 and binarycache using node_exporter metrics
=> Add initial monitoring server configuration

.reuse/dep5, flake.lock.license, hosts/binarycache/secrets.yaml.license, hosts/build01/secrets.yaml.license, hosts/common.nix, hosts/ghafhydra/secrets.yaml.license, hosts/monitoring/secrets.yaml.license, terraform/secrets.yaml.license
- Use dep5 to replace `.license` files: https://reuse.software/faq/#bulk-license
- Add ghaf-dev.cachix.org substitutre, since it's now also used in Ghaf: https://github.com/tiiuae/ghaf/blob/aef5ad3a916b51c33f23163b657045bd2f9f4df8/flake.nix#L22
=> Use dep5 license

hosts/binarycache/default.nix
The automatic gc was deleting for example provenance files from the cache, causing issues in jenkins pipelines.
=> Don't run automatic gc on cache

flake.lock
The current version seems bad, there's a fixed-output derivation mismatch somewhere in the python tooling:
```
> error: hash mismatch importing path '/nix/store/c3cjxhn73xa5s8fm79w95d0879bijp04-python3-3.10.13';
>          specified: sha256:0psh4a7hf891sfc6z38qb3a3jxb1jzljym2kfw3p4i4x409989mr
>          got:       sha256:1i6kl621m9gm2i2f6p3qm36wqvwh654rfhz0z6hc3fa93a0cngmp
> copying path '/nix/store/b4fk2q4zn8z1bf9zf19lhf8iygs2z3b7-command-not-found' to 'local'...
```
=> flake.lock: bump nixpkgs

hosts/default.nix, hosts/ficolobuild/configuration.nix, hosts/ficolobuild/disk-config.nix, tasks.py, users/default.nix, users/mkaapu.nix
Add common configuration to install NixOS for all Ficolo build servers replacing current Ubuntu servers
HW configuration is based on configuration generated by the nixos-generate-config tool on one of the target machines.
Preconfigured IP address is provided to Ficolo builders by an external DHCP server based on the MAC address of the server.
Disk configuration (disk-config.nix) formats 4 separate disks. Initial disk setup should be identical on all Ficolo build servers.
Configuration alias to install NixOS to the current build3 Ubuntu machine with the IP address 172.18.20.104 added.
The 'mkaapu' user account configuration added.
All existing users will be added to installed Ficolo build machines.
=> Add Ficolo builder configuration

docs/monitoring-server.md, hosts/binarycache/configuration.nix, hosts/default.nix, hosts/ficolo-hosts.nix, hosts/monitoring/configuration.nix, hosts/monitoring/secrets.yaml, hosts/qemu-common.nix, pkgs/sshified/default.nix, services/node-exporter/default.nix
[sshified](https://github.com/hoffie/sshified) can be used to proxy prometheus metrics through ssh connection, meaning we do not have to open any ports to the world.
This PR adds a derivation to build `sshified`, a systemd service to run it, and the necessary ssh configuration to scrape metrics from awsarm.
Also added documentation that tells how to add new monitored targets, with either ssh or http authentication, though there are no more targets that are using http basic auth.
=> Monitor awsarm through SSH

hosts/ficolobuild/configuration.nix
Add access to extra hosts:
Add access to vedenemo.dev to fetch Gala app sources.
Add access to cache.vedenemo.dev (Binary cache).
=> x86 builder: Add access to binary cache and Gala app sources

hosts/default.nix, hosts/prbuilder/configuration.nix, hosts/prbuilder/disk-config.nix, tasks.py, users/default.nix, users/karim.nix
Configure NixOS for "prbuilder" with Docker support, user management, and network settings.
=>  Add Ficolo PRBUILDER  configuration 

hosts/prbuilder/configuration.nix, tasks.py
Current main branch does not pass `nix flake check` as the formatting is wrong in prbuilder configuration. This passed our automatic checks because the pre-push task silently reformats the files before running `nix flake check`. Thus the pre-push checks pass even though files have been changed.
`nix fmt` has no `--check` option so this was changed to ~~`alejandra --check .`~~ `nix fmt -- --fail-on-change`.
For `tasks.py`, added some commas so `black` will format the aliases consistently in the same way. Without this the wrapping would depend on the line length. Imports have also been sorted with `isort`.
=> Fix pre-push formatting checks

hosts/binarycache/configuration.nix, hosts/ficolobuild/configuration.nix, hosts/ghafhydra/configuration.nix, hosts/monitoring/configuration.nix, hosts/prbuilder/configuration.nix, users/default.nix, users/tervis.nix
Selfishly adding myself as admin to all hosts
=> Add user tervis to all hosts

hosts/ficolo-hosts.nix, hosts/ficolobuild/configuration.nix
General ficolohosts module defining extra hosts were tested and introduced after x86 builder configuration.
- Removing extra hosts configuration from hosts/ficolobuild/configuration.nix
- Including ficolohosts module
- This also fixes a bug caused by using double quotation marks instead of single ones to list extra hosts in configuration, which added extra spaces before the IP addresses in /etc/hosts which are not allowed.
Extra commit: Ganymede is taken down so removing that from extra hosts.
=> x86 builder: Include ficolohosts module

hosts/prbuilder/configuration.nix
Add necessary py3 dependencies for the PR builder
=> Add py3 dependencies for the PR builder

flake.lock, flake.nix, hosts/common.nix
23.05 has outdated grafana module which no longer works properly. Updating to 23.11 fixes the monitoring dashboard.
Requires verifying on all hosts that the update doesn't introduce breaking changes. Raising the stateVersion *should* be fine as we don't really have much state that could break.
`monitoring-ficolo` and `binarycache-ficolo` have been succesfully updated and show no recession.
=> Update nixpkgs to 23.11

.gitignore, terraform/jenkins/binary_cache.tf, terraform/jenkins/binary_cache_signing.tf, terraform/jenkins/binary_cache_storage.tf, terraform/jenkins/builder.tf, terraform/jenkins/image_storage.tf, terraform/jenkins/jenkins_controller.tf, terraform/jenkins/main.tf, terraform/jenkins/remote_build_ssh.tf, terraform/playground/README.md, terraform/playground/terraform-playground.sh, terraform/playground/test-infra.tf
Support using terraform workspaces to setup private development environments on Azure:
- Adds `playground/terraform-playground.sh` to facilitate the usage of private development environments in testing infrastructure changes
- Adds terraform workspace support for ghaf-infra-jenkins to make it possible to use the playground tooling to support setting-up temporary development environments of the ghaf-infra-jenkins infrastructure.
=> playground: initial version

hosts/default.nix, hosts/ficolobuild/build3.nix, hosts/ficolobuild/builder.nix, tasks.py
Changes:
- adds build3 (x86 builder on Ficolo) specific configuration
- adds Barna as a trusted user to build3 specific configuration
- hostname of build3 machine changed from "nixos" to "build3"
Notes:
- Hostname change will not take place without running the hostname tool or without reboot
=> Separate machine specific x86 builder configuration from the common one

hosts/default.nix, hosts/ficolobuild/build4.nix, tasks.py
- adding configuration for build4 Ficolo x86 builder (ficolobuild4)
- adding alias (build4-ficolo) for deployment tasks
=> Configure NixOS for build4 x86 Ficolo builder

.gitignore
Switching between main branch and azure-images branch leaves dirty git state because these files are only ignored on the other branch. This should fix that temporarily.
=> Ignore tmp files in main branch

hosts/ficolobuild/build4.nix
The build4 (x86 Ficolo build server) will be used as remote builder with Themisto Hydra.
=> Add themisto user to build4

hosts/ficolobuild/build3.nix, users/default.nix, users/ktu.nix
Also adds `wheel` group as trusted user so any admins can use the remote builder
=> Add kai as admin user to build3

hosts/builder/configuration.nix, hosts/jenkins-controller/configuration.nix, terraform/main.tf, terraform/persistent/main.tf, terraform/playground/README.md, terraform/playground/terraform-playground.sh, terraform/terraform-init.sh
Allow many instances of 'persistent' data based on workspaces. This makes it possible to have separate 'persistent' data, for instance, by Azure location. Assumes default location is 'northeurope'.
=> terraform: allow many persistent instances

hosts/ficolobuild/developers.nix, services/openssh/default.nix, users/barna.nix, users/karim.nix
RSA keys are not secure and we should not allow them in this repo.
> [OpenSSH 9.5](https://www.openssh.com/releasenotes.html) (2023-10-04) includes [ssh-keygen(1)](https://man.openbsd.org/ssh-keygen.1) which now generates Ed25519 keys by default.
=> Stop using RSA

hosts/azure-common.nix, hosts/azure/jenkins-controller/configuration.nix
Fix Jenkins service startup:
- Delay jenkins service startup by making it run after `multi-user.target`.
- Add a comment pointing to future work for improving the cloud-init usage together with azure agent.
- Make both `cloud-config.service` and `jenkins.service` restart on failure.
=> Fix jenkins service startup

.github/workflows/check-commit-message.yaml, README.md, githooks/check-commit.sh, githooks/check-commits.sh, githooks/install-git-hooks.sh
Added scripts to check commit messages
Updated README.md about commit message hooks
Added github action to check commit messages on push
=> Add commit message checks to ghaf-infra

hosts/ficolobuild/build3.nix, hosts/ficolobuild/build4.nix, hosts/ficolobuild/builder.nix
- Environment for Yubikey provisioning (legacy Hydra builds)
- Add Yubikey signer accounts for build3 and build4
=> remote x86 hydra builder: Add Yubikey provisioning

hosts/azure/jenkins-controller/configuration.nix, terraform/jenkins-controller.tf, terraform/main.tf, terraform/persistent/workspace-specific/main.tf, terraform/terraform-init.sh
- Configure Jenkins: install pipeline and github plugins, allow anonymous read access, disable setup wizard, install packages required by Jenkins pipeline.
- Configure build pipeline job based on the pipeline script now maintained in a separate repo at: https://github.com/tiiuae/ghaf-jenkins-pipeline.
- Deploy caddy reverse proxy, redirecting public HTTPS requests to jenkins service on the jenkins-controller VM. No need to open port 80 as caddy can deploy let's encrypt certificates using tls-alpn-01 (over HTTPS).
- Adds a 'persistent' state disk on jenkins-controller VM to store let's encrypt data for caddy.
=> jenkins-controller: Initial Jenkins configuration

terraform/binary-cache.tf, terraform/builder.tf, terraform/jenkins-controller.tf, terraform/modules/azurerm-linux-vm/variables.tf, terraform/modules/azurerm-linux-vm/virtual_machine.tf
Default osdisk sizes:
- jenkins-controller: 150 GB
- builder: 150 GB
- binary-cache: 50 GB
=> Make osdisk size configurable

hosts/azure/jenkins-controller/configuration.nix
Install Jenkins plugin 'timestamper' to support enabling timestamps for the pipeline logs.
=> jenkins-controller: Jenkins timestamper plugin

hosts/azure/jenkins-controller/configuration.nix, terraform/main.tf
- Perform better when low on memory; 'priv' and 'dev' environments should be able to run the [Jenkins pipeline](https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/main/ghaf-build-pipeline.groovy) by default without OOM. Also, if running out-of-memory, try to prioritize keeping the Jenkins service alive.
- Adjust image sizes so 'priv' environments should also be able to run the Jenkins pipeline by default. Currently, it seems the Ghaf target evaluation is not possible with 8GiB RAM, therefore, increasing the 'priv' Jenkins controller VM to 'Standard_E2_v5' (which has 16GiB RAM).
- Increase the binary cache VM size from 'Standard_D1_v2' to 'Standard_D2_v3' since the cost impact is relatively small (versus the cost of time spent when people need to debug possible resource issues).
- Start …
=> Perform better on low memory

hosts/azure/binary-cache/configuration.nix, hosts/azure/jenkins-controller/configuration.nix, terraform/binary-cache.tf, terraform/jenkins-controller.tf
Move caddy environment file from `/run/caddy.env` to `/var/lib/caddy/caddy.env` to make it persist reboots. Before this change, caddy service would fail to start after the first boot due to missing caddy environment file.
=> Fix caddy startup

hosts/ficolobuild/build3.nix, hosts/ficolobuild/build4.nix, hosts/ficolobuild/developers.nix, users/barna.nix, users/builder.nix, users/cazfi.nix, users/hrosten.nix, users/hydra.nix, users/jrautiola.nix, users/karim.nix, users/ktu.nix, users/mika.nix, users/mkaapu.nix, users/tervis.nix, users/tester.nix, users/themisto.nix
Adding the description field for user accounts, for normal people users in Linux this is usually the full name of the user.
For system accounts this can be a more elaborate description.
=> Add real names for users

terraform/playground/test-infra.tf
When attempting to execute the Terraform configuration in test-infra.tf, an error occurs due to a missing required argument. Specifically, the virtual_machine_osdisk_size argument is not defined within the module "test_vm",
=> Resolve test-infra.tf

terraform/playground/test-infra.tf
After recent changes, the nixosConfiguration name 'builder' has been replaced with 'az-builder'.
=> Replace builder to az-builder

terraform/modules/azurerm-nix-vm-image/nix-build.sh
This file was initially vendored from the TVL repo.
abe836b4f223ea3f3b89ce106c0d258074680589 accidentially updated the copyright header with the default TII header, but the actual copyright header needs to be preserved.
=> nix-build.sh: correct copyright header

ssh-keys.yaml, terraform/jenkins-controller.tf
New user for Jenkins Controller (mika)
=> Jenkins: Add user mika

terraform/jenkins-controller.tf
This is workaround to allow more build records to be stored on Jenkins home directory.
My suggestion to continuation work:
Separate store for Jenkins workspace
- for proper CI control / build isolation, Jenkins master node should have 0 executors and all working directories should reside in agent machines.
Separate jobs configuration, build records and artifacts from Jenkins home
- one solution: symbolic links to another store
- build artifacts may needs some more persistent store separate from other build records
=> Jenkins controller: Increase jenkins home disk size

terraform/arm-builder.tf, terraform/jenkins-controller.tf, terraform/main.tf, terraform/modules/arm-builder-vm/variables.tf, terraform/modules/arm-builder-vm/virtual_machine.tf, terraform/modules/azurerm-linux-vm/variables.tf, terraform/modules/azurerm-linux-vm/virtual_machine.tf
Hard-code the arm builder location to 'northeurope' due to limited support of arm-based VMs in many other Azure regions. Specifically, ghaf-infra deployment on UAE would fail without this change, since Azure UAE locations do not support arm-based VMs. The workaround done in this change is to always deploy the arm-builder on 'northeurope', even if other ghaf-infra resources are deployed on locations other than eun.
For reference: this PR implements the workaround proposed in: https://github.com/tiiuae/ghaf-infra/pull/81#pullrequestreview-1927417660
=> arm-builder: Always deploy arm-builders to eun

terraform/arm-builder.tf, terraform/modules/arm-builder-vm/ubuntu-builder.sh.tpl, terraform/modules/arm-builder-vm/variables.tf, terraform/modules/arm-builder-vm/virtual_machine.tf
Configure the trusted-public-keys in Ubuntu ARM builders based on the `binary_cache_public_key` configuration option in terraform the root module. Also, support setting the `binary_cache_url` on the Ubuntu ARM builders similarly.
For reference: this PR implements the change outlined in an earlier PR at: https://github.com/tiiuae/ghaf-infra/pull/106#issuecomment-2014565749
=> Ubuntu arm-builder: Configurable trusted-public-keys

hosts/azure/binary-cache/configuration.nix, hosts/azure/builder/configuration.nix, hosts/azure/jenkins-controller/configuration.nix, services/default.nix, services/rclone-http/default.nix
Replaced copypasted rclone-http services with a reusable module, with configurable options. The caddyfile workaround is also removed as the fix has been merged into nixpkgs and backported to our version.
=> Refactor rclone-http into a module

hosts/binarycache/configuration.nix, hosts/ficolobuild/build3.nix, hosts/ficolobuild/build4.nix, hosts/ficolobuild/builder.nix, hosts/monitoring/configuration.nix, hosts/prbuilder/configuration.nix
We can simply concatenate lists with the `++` operator, no need to call lib.flatten on a list of lists to archieve the same thing.
Also, remove the surrounding with statement in case it's only used once or twice, and sort file imports before others.
=> hosts/*: remove lib.flatten usage

terraform/main.tf
Change the `binary_cache_public_key` in the root terraform module to match the pubkey used in testing the `prod` deployment.
=> terraform: Initial prod sigkey

hosts/testagent/brainstem.nix, hosts/testagent/configuration.nix
This adds support for the Acroname USB Smart switch connected to the system. We vendor in the expression until our nixpkgs pin moves past its inclusion into nixpkgs.
=> testagent: support Acroname USB Smart switches

hosts/ficolobuild/build4/configuration.nix
-ACME: config protocol is used for automated domain-validated SSL certificates. The configuration is updated to accept the terms of Let's Encrypt, automated, and open Certificate Authority that uses the ACME protocol. The default email`trash@unikie.com`.
-Nginx config: includes enabling ACME for SSL certificate management, forcing SSL for secure connections, and setting this as the default server block!
-root location (`/`) for this server is configured to proxy pass to `http:127.0.0.1:3015`
=> Nixos configuration build4 for the pandia.vedenemo.dev

hosts/monitoring/configuration.nix
Refactor changes to the Prometheus scrape configurations for the ficolo-internal-node-exporter job. 
We have added static configurations for several targets, each with a unique IP address and port (9100). Each target has been assigned a label indicating the machine name
These changes will  improve the monitoring of our services by providing more detailed and specific metrics from different machines.
=> Refactor monitoring nix configuration

flake.lock, flake.nix, hosts/testagent/configuration.nix
[ci-test-automation](https://github.com/tiiuae/ci-test-automation) is added as a flake input as it exposes `ghaf-robot` package for use. The package is then installed onto test agent. This allows robot framework tests to be run. Also merged some repeated options.
=> Add robot framework packages to test agent

hosts/azure/binary-cache/configuration.nix, hosts/azure/jenkins-controller/configuration.nix, terraform/binary-cache.tf, terraform/jenkins-controller.tf
This needs to be reachable for the HTTP-01 challenge to work.
WIthout it, a fresh deployment is unable to get a new certificate (as it tries HTTP-01, times out and backs off).
Configuring caddy to use TLS-ALPN-01 only is too annoying to do - we cannot use the Caddyfile config, but would need to fall back to the internal JSON config format.
We don't expose any vhost via http only, this only serves HTTP challenges.
=> az-{jenkins-controller,binary-cache}: re-enable HTTP port

hosts/ficolobuild/developers.nix
Grants an access to a new developer for x86 remote builder.
=> x86 builder: Add shamma as developer

terraform/test-deployment.sh
- Adds support for testing end-to-end build with different architectures. Adds a testcase to check the end-to-end build works on aarch64.
- Make the script output more informative.
- Remove the OUT variable, which was mostly a leftover from an earlier (local) version of the script.
=> test-deployment.sh: Add a test for aarch64 builds

terraform/test-deployment.sh
- Wait until service is past 'activating' state or at most 60 seconds before running the systemctl status check for each service.
- Allow escape characters in each test output details.
=> test-deployment.sh: Wait services past activating

hosts/azure-common.nix
Stop automatic garbage collector on Azure hosts. Before this change, gc automatically ran daily at [03:15](https://search.nixos.org/options?channel=unstable&show=nix.gc.dates&from=0&size=50&sort=relevance&type=packages&query=nix.gc).
We don't want to run it automatically, but only when `/nix/store` storage drops below certain threshold. For that, we already have `nix.settings.min-free` and `nix.settings.max-free`, the values of which are also adjusted in this PR.
Before this change, the nigthly gc would effectively clean the `/nix/store` unnecessarily removing earlier local build results. Thus, the configuration before this change triggered unnecessary downloads from the Azure blob storage when the nix store was re-populated on the first build after the daily cleanup. The …
=> az-common: Stop automatic daily gc

terraform/modules/arm-builder-vm/ubuntu-builder.sh.tpl
Adds `WantedBy` section to the systemd service created by the ubuntu script. It now starts properly when the vm is restarted.
=> Fix rclone service not starting on azure arm

hosts/builders/build3/configuration.nix, hosts/builders/build4/configuration.nix, hosts/builders/cross-compilation.nix, hosts/builders/hetzarm/configuration.nix, hosts/common.nix, users/themisto.nix
- This makes it possible to build `#packages.aarch64-linux.nxp-imx8mp-evk-debug` on x86
- Also simplified trusted users configuration.
=> Add aarch64 emulation for builders using binfmt

terraform/main.tf
Replace two 8-core Azure builder VMs with one 16-core on the `prod` environment. Combined price does not change, but we gain increased RAM (32G --> 64G) on the builder(s).
=> prod: Replace two small builders with one big

terraform/main.tf
Beef-up jenkins-controller VM on the priv instance(s) to the same VM size as what is already used in dev. This is needed since 16GiB RAM on jenkins-controller is simply no longer enough to evaluate the Ghaf flake targets (the evaluation needs to happen on the jenkins-controller).
=> Beef-up priv jenkins-controller

hosts/azure/builder/configuration.nix
With this change, imx8mp target can be built on azure.
=> Enable aarch64 emulation on azure x86 builders

hosts/binarycache/configuration.nix, hosts/common.nix
This is the same garbage-collection change that was earlier done for Azure hosts in PR: https://github.com/tiiuae/ghaf-infra/pull/145:
> Before this change, gc automatically ran daily at [03:15](https://search.nixos.org/options?channel=unstable&show=nix.gc.dates&from=0&size=50&sort=relevance&type=packages&query=nix.gc).
We don't want to run it automatically, but only when /nix/store storage drops below certain threshold. For that, we already have nix.settings.min-free and nix.settings.max-free, the values of which are also adjusted in this PR.
>
> Before this change, the nigthly gc would effectively clean the /nix/store unnecessarily removing earlier local build results. Thus, the configuration before this change triggered unnecessary downloads from the Azure blob storage when the nix …
=> common: Stop automatic daily gc

hosts/azure/jenkins-controller/configuration.nix, hosts/azure/jenkins-controller/jenkins-casc.yaml
The configuration-as-code plugin is the recommended way to configure
Jenkins, not the Groovy script. Most plugin settings seem to be
available through that.
The yaml was produced by checking in the dump created by the plugin.
---
azure/jenkins-controller: enable safe-html
This allows configuring HTML descriptions for build descriptions, which
we'll use to link to artifacts in the future.
=> jenkins: migrate to configuration-as-code, enable html markup

hosts/azure/jenkins-controller/configuration.nix, pkgs/rclone/default.nix, pkgs/rclone/webdav-introduce-unix_socket_path.patch, terraform/jenkins-controller.tf, terraform/main.tf
Depends on #160, will be rebased once merged (so ignore the first 2 commits).
This adds the necessary services running on the jenkins-controller machine to upload and serve artifacts from Azure storage.
- A per-environment storage container for artifacts is added via terraform
- Two rclone services exposing the bucket contents, rw and ro, plus config to expose the ro part via caddy.
- Our rclone gains another patch/feature, support to connect to webdav backends via unix domain sockets, and that rclone is made available in jenkins' `$PATH`.
=> jenkins: preparations to upload and serve artifacts

terraform/main.tf, terraform/persistent/main.tf, terraform/state-storage/tfstate-storage.tf
Fail terraform plans that require ghaf-infra-persistent or azure state storage to be destroyed. This only protects against accidental client-side destruction.
Also, protect against accidental dev or prod environment deployment by requiring variable -var="convince=true" when deploying to environment types other than priv.
=> terraform: Prevent accidental destroy/deployment

hosts/builders/developers.nix
Add a temporary user for Azure dev remote builds on hetzarm (hetzarm.vedenemo.dev) and ficolo (builder.vedenemo.dev).
=> Add temporary remote-build user

terraform/jenkins-controller.tf
This adds builder.vedenemo.dev and hetzarm.vedenemo.dev as static builders to /etc/nix/machines, as well as the keyscan machinery.
https://github.com/tiiuae/ghaf-infra/pull/171 already ensured that ssh key works.
maxJobs is set to the number of cores the system sees, and speedFactor is set to 3, making it more attractive than the other builders.
=> terraform/jenkins-controller: add static builders

hosts/azure-common.nix, terraform/jenkins-controller.tf, terraform/main.tf
Azure builders are no longer needed on 'priv' and 'dev' environments after https://github.com/tiiuae/ghaf-infra/pull/173.
This change also moves the external builder configuration to the environment-specific configuration options to anticipate ghaf-infra deployments on locations that might not want to use the vedenemo.dev builders we are using with Ghaf.
Adds the `tree` package since it would be nice to have on the Azure hosts, but also to make sure this change triggers an update in the terraform infra, see: https://ssrc.atlassian.net/browse/SP-3899 which still needs fixing.
=> Remove azure builders

hosts/monitoring/configuration.nix, pkgs/sshified/default.nix
- awsarm is no longer being monitored
- now monitoring the monitoring server itself
- sshified updated to [v1.1.19](https://github.com/hoffie/sshified/releases/tag/v1.1.19) for security updates and bug fixes
=> Update monitoring, remove awsarm

hosts/monitoring/configuration.nix
Fixes issue where monitoring dashboard graphs would show "no data" in timeframes lower than 24 hours, due to scrape interval being `1m` in prometheus and `15s` in grafana datasource
=> Reduce scrape interval to fix dashboards mismatch

.github/workflows/test-ghaf-infra.yml, hosts/builders/developers.nix, hosts/builders/hetzarm/configuration.nix, tasks.py
- Added hetzarm as remote builder so aarch64 configs can be built.
- Added build3 as remote builder to speed up building of the x86 targets.
- Added authentication steps to the workflow now that we are dealing with secrets and have to use `pull_request_target`. The auth steps are similar what is being used in ghaf repo but simplified. Reasoning explained here https://ssrc.atlassian.net/wiki/x/OABjMg
FYI the checks for this PR will fail as it's not able to use the secrets yet.
Tests done in my fork using alt account to make different PRs https://github.com/joinemm/ghaf-infra/pulls
=> Add aarch64 checks and auth to workflow

hosts/testagent/configuration.nix
Includes the following testagent changes, preparing it to run HW-tests for the Azure ghaf-infra 'dev' instance:
- Make wget available for the jenkins agent
- Move the jenkins-connection service's exec start to it's own script
- Add some basic error checks for the jenkins-connection service
- Configure start rate limiting for the jenkins-connection service
- Connect testagent to dev jenkins-controller
=> testagent: Prepare for HW-testing in 'dev'

.github/workflows/test-ghaf-infra.yml
Username was not being detected properly because the indentation of the script was causing additional whitespace on the lines when echoed. This whitespace caused grep to not match. The fix is replace any repeated whitespace with newlines.
=> Fix whitespace issues in workflow

.sops.yaml, hosts/default.nix, hosts/ghaf-log/configuration.nix, hosts/ghaf-log/disk-config.nix, hosts/ghaf-log/secrets.yaml, tasks.py, users/bmg.nix, users/default.nix, users/vilvo.nix, users/vunnyso.nix
Barebones hetzner configuration. Server is CX32 with 100gb block volume attached. User details for bmg, vilvo and vunnyso copied from `developers.nix` into admin user modules.
=> Add initial ghaf logging server configuration

terraform/jenkins-controller.tf, terraform/main.tf
Prod is only created for the duration of the build so the cost increase is negligible. This should speed up the builds.
=> Use 64 core builders in prod environment

hosts/azure/jenkins-controller/configuration.nix
This PR implements the jenkins-controller VM changes required to support jenkins HW-testing pipelines.
This change depends on the pipeline changes from: https://github.com/tiiuae/ghaf-jenkins-pipeline/pull/34.
Note: running the HW-tests requires setting-up a testagent as described in: https://ssrc.atlassian.net/wiki/x/IoAXRQ - currently, such testagent setup will be done on the 'dev' instance. Other instances are still able to run the pipelines, but the HW-tests will obviously not be run unless testagent is connected.
=> jenkins-controller: Changes to support hw-testing

.github/workflows/test-ghaf-infra.yml
- Added `ghaf-dev` cachix cache to be used in the test workflow. Derivations that were always built again and again, such as terraform, are now pushed to the cache and will be copied on subsequent runs of the workflow.
- Increased max-jobs to 4. Github runners have 4 cores and most of the jobs are only copying or doing small builds so this should be fine.
With these changes, the average workflow duration for a small change dropped from ~15 minutes to ~7 minutes; making it 200% faster.
=> Use cachix cache to speed up checks

hosts/builders/build3/configuration.nix, hosts/builders/build4/configuration.nix, hosts/builders/builders-common.nix, hosts/builders/hetzarm/configuration.nix
Fixes occasional build failures when the builders are being used by many clients at the same time and >10 ssh connections are authenticating simultaneously.
`journalctl -u sshd | grep MaxStartups` shows that the issue happens every few days on hetzarm:
```
Jun 24 04:01:33 hetzarm sshd[2072]: exited MaxStartups throttling after 00:02:10, 31 connections dropped
Jun 24 11:53:18 hetzarm sshd[2072]: error: beginning MaxStartups throttling
Jun 24 11:53:18 hetzarm sshd[2072]: drop connection #17 from [112.6.161.100]:52488 on [65.21.20.242]:22 past MaxStartups
Jun 24 11:53:49 hetzarm sshd[2072]: drop connection #18 from [112.6.161.100]:32798 on [65.21.20.242]:22 past MaxStartups
Jun 24 11:54:14 hetzarm sshd[2072]: drop connection #19 from [112.6.161.100]:48962 on [65.21.20.242]:22 past …
```
=> Increase sshd MaxStartups to 100 on builders

services/openssh/default.nix
This is temp fix for [CVE-2024-6387](https://github.com/advisories/GHSA-2x8c-95vh-gfv4) before we can update to nixos 24.05
=> Mitigate CVE-2024-6387

hosts/ghaf-log/configuration.nix, hosts/ghaf-log/disk-config.nix
When hetzner cloud box is rebooted with a block volume attached, the block volume can become `/dev/sda` and the root disk change to `/dev/sdb`. Trying to deploy after this bricks the server as it tries to install grub onto the mounted block volume. 
Fix is to use more specific name for the disk. `pci-0000:06:00.0-scsi-0:0:0:0` should always point to the root disk.
=> Use more specific disk names in hetzner

hosts/azure/jenkins-controller/jenkins-casc.yaml, terraform/jenkins-controller.tf
Specify the HTTP address of the Jenkins installation.
The address is written to a file when jenkins-controller VM is created.
Jenkins Configuration as Code plugin (JCasC) reads the address from that file.
=> Specify the Jenkins URL with JCasC

hosts/monitoring/configuration.nix
Add missing public key for ghaf-log monitoring target and make the sshiefied service restart when known_hosts is changed.
=> Add restart trigger for sshified

hosts/ghaf-log/configuration.nix, hosts/ghaf-log/loki.nix, hosts/ghaf-log/secrets.yaml
- Grafana available at `https://ghaflogs.vedenemo.dev`, requires login to view.
- Loki push endpoint available at `https://loki.ghaflogs.vedenemo.dev`, behind basic auth username and password.
- Access using insecure ip:port and http no longer possible, firewall gaps closed.
- Applied security hardening options for Grafana.
=> Security hardening for ghaf logging server

hosts/testagent/configuration.nix
Commit 7d960b8523eafcb2cb9be1e438ee2c248a4dcee0 changed the OrinAGX1 plug configuration type from TAPOP100v2 to TAPOP100, which apparently broke the boot tests on OrinAGX. This commit reverts the OrinAGX1 plug_type to what it was before 7d960b8523eafcb2cb9be1e438ee2c248a4dcee0.
Plug type TAPOP100 needs a fix in `ci-test-automation` repo, which will be done later with a separate PR: https://github.com/tiiuae/ci-test-automation/pull/125.
=> testagent: Fix OrinAGX1 plug_type

nix/devshell.nix
Use azurerm version v3.9.85 which is the current latest version not impacted by the issue described in:
https://github.com/hashicorp/terraform-provider-azurerm/issues/24444.
As soon as there's an azurerm upstream fix for the issue, we should move the override to that version. The override will no longer be needed when the azurerm version we get from the nixpkgs pinned in ghaf-infra ships with azurerm version that includes the fix.
=> terraform-azurerm: Use azurerm v3.9.85

hosts/testagent/configuration.nix
We need it both in udev packages and systemPackages, as the package
brings binaries to interact with it, and udev rules to control
permissions.
We still might need to tweak these, as they make use of the `uaccess`
tag, which didn't seem to work for jenkins.
=> hosts/testagent: add usbsdmux 

terraform/main.tf
This change adds another name for the 'dev' binary cache: `dev-cache.vedenemo.dev`.
The value of environment-specific terraform variable 'binary_cache_url' is read in the Caddy configuration from the SITE_ADDRESS variable, populated on the binary cache host via the `/var/lib/caddy/caddy.env` file.
Caddy supports comma separated site addresses as documented in: https://caddyserver.com/docs/caddyfile/concepts#addresses so we can directly use the same syntax in the 'binary_cache_url' terraform variable.
Caddy will also automatically take care of obtaining and renewing Let's Encrypt certificates for all the site addresses: https://caddyserver.com/docs/automatic-https.
=> main.tf: Add hard-coded name for dev bincache

terraform/main.tf
Increase binary cache vm size on 'dev' (and 'prod') environment(s) preparing for wider usage of ghaf-infra 'dev' binary cache.
=> Increase binary cache vm size

.github/workflows/schedule-update-actions.yml
Adding GitHub Actions workflow to automatically update the versions of actions used in the ghaf-infra. The workflow runs on a weekly schedule and uses the 'saadmk11/github-actions-version-updater' action.
FYI: A pull request will be created with the title "ci: Update GitHub Actions to Latest Version" if updates are available.
=> Add workflow version updater

scripts/test-nix-cache.sh
Add `test-nix-cache.sh`:
```
Usage: test-nix-cache.sh [-h] [-v] [-o OUTFILE] -b BINCACHE -k KEY -f FLAKEREF 
Perform basic download test for the given binary cache.
The script attempts to download the FLAKEREF closure from the given
binary cache, outputting the time the cache download took.
Script fails unless the full closure is available on the binary 
cache - it will not attempt to rebuild anything.
Script makes use of a temporary nix store so possible earlier cached
content on the local nix store will not be used by the nix build
command the script invokes.
Options:
-h    Print this help message
-v    Set the script verbosity to DEBUG
-o    Set the script output file to OUTFILE
-b    Set the target binary cache
-k    Set the target binary cache trusted public key
-f    Set the target …
```
=> test-nix-cache.sh: Initial version

terraform/terraform-playground.sh
terraform/terraform-playground.sh: It's better to let `terraform init` output to console.
=> terraform-playground.sh: Init out to console

terraform/modules/azurerm-nix-vm-image/main.tf
Set to 1h, doubling it from the default of 30m.
=> Increase blob storage create timeout

terraform/main.tf, terraform/terraform-init.sh, terraform/terraform-playground.sh
Make terraform emit an error message in case the azurerm version cached in local `.terraform` directory on the main terraform module does not match the version we require.
Make `terraform-init.sh` invoke the command `terraform init` with `-upgrage` option so the terraform plugin versions cached in local `.terraform` directory would be updated on updating the pinned terraform plugin versions - they are pinned in ghaf-infra flake devshell and should be updated when flake updates.
=> Invoke terraform init with upgrade option

hosts/ghaf-log/configuration.nix, hosts/ghaf-log/secrets.yaml
Navigating to https://ghaflogs.vedenemo.dev now presents the user with "Sign in with Github" button. If the logged in Github user is part of the `tiiuae` org, and the `devenv-fi` or `phone` teams, they are allowed access to the grafana instance. ~~The default grafana login with username and password is no longer possible.~~
Grafana account is created for every user when they first log in:
=> Github OAuth for ghaf-log grafana instance

hosts/testagent/configuration.nix
Fix for lenovo-x1 testagent configuration.
There was naming issue of controlling right device button pressers.
=> HW test configuration file fix

nix/devshell.nix
This ensures `nixfmt` is in $PATH too, which ensures text editors pick it up in case they're configured to use `nixfmt`.
=> devshell.nix: add nixfmt-rfc-style

hosts/azure/jenkins-controller/configuration.nix
Rename `ghaf-test-boot` to `ghaf-hw-test` after https://github.com/tiiuae/ghaf-jenkins-pipeline/pull/45
=> jenkins-controller: Rename test pipeline

terraform/test-deployment.sh
After https://github.com/tiiuae/ghaf-infra/pull/228, Azure binary-cache no longer runs rclone-http. This change removes the manual rclone-http service restart from the test-deployment.sh script as it is no longer needed (and triggers an error in the test script).
=> Fix test-deployment.sh: Remove rclone restart

hosts/testagent/configuration.nix, hosts/testagent/hardware-configuration.nix
This commit includes the following changes based on intial testing with the riscv HW on `testagent`:
- Add udev rule for riscv serial connection symlinking it to `/dev/ttyRISCV1`
- Change jenkins test config to make it use the new `/dev/ttyRISCV1` serial port for `Polarfire1` configuration
- Add kernel module `sg` to testagent configuration, this is needed by usbsdmux: https://github.com/linux-automation/usbsdmux#troubleshooting
=> testagent: Fix riscv support

hosts/common.nix
Add any wheel users as nix trusted users, this fixes trusted key issues that occasionally show up when deploying locally built changes on remote machines:
```
copying path '/nix/store/...' to 'ssh://xxx'
error: cannot add path '/nix/store/...' because it lacks a signature by a trusted key
```
https://github.com/NixOS/nixpkgs/issues/159082#issuecomment-1118968571
=> Add wheel to nix trusted users for all hosts

scripts/get-artifacts.sh
Initial version of script `get-artifacts.sh`, which is just a wrapper around `wget` and `tar` to help release managers download the release content so its available on local host.
Example: download results of one build target ([packages.x86_64-linux.doc](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/artifacts/ghaf-release-pipeline/build_1-commit_d66c087b2ae3d6b02732e68c01f6ad59dfdaabbb/packages.x86_64-linux.doc/) in this case):
```
./scripts/get-artifacts.sh -u https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/artifacts/ghaf-release-pipeline/build_1-commit_d66c087b2ae3d6b02732e68c01f6ad59dfdaabbb/packages.x86_64-linux.doc
```
Another example: download results of all build targets from one build …
=> Initial version of get-artifacts.sh

.sops.yaml, hosts/default.nix, hosts/ghaf-coverity/configuration.nix, hosts/ghaf-coverity/disk-config.nix, hosts/ghaf-coverity/secrets.yaml, nix/deployments.nix, tasks.py, users/default.nix, users/fayad.nix
Adds new Hetzner VM host: `ghaf-coverity`, with barebones NixOS configuration, and admin user for Fayad.
=> Add initial configuration for ghaf-coverity server

.github/workflows/check-commit-message.yaml, .github/workflows/schedule-update-actions.yml, .github/workflows/test-ghaf-infra.yml
* **[actions/checkout](https://github.com/actions/checkout)** published a new release **[v4.1.7](https://github.com/actions/checkout/releases/tag/v4.1.7)** on 2024-06-12T19:05:21Z
* **[tj-actions/changed-files](https://github.com/tj-actions/changed-files)** published a new release **[v45.0.1](https://github.com/tj-actions/changed-files/releases/tag/v45.0.1)** on 2024-09-02T00:05:11Z
=> Update GitHub Actions to Latest Version

hosts/azure/jenkins-controller/configuration.nix
Increase the number of rows shown in the 'Stage View' for all pipelines. The default seems to be 10 rows, this commit changes it to 32 rows to be able to glance the Stage View build history a bit further.
=> jenkins-controller: Increase stage view rows

pkgs/rclone/default.nix
This links to the comment, so once we bump nixpkgs to a version including rclong 1.68.0 we know we can just drop this entirely.
=> rclone: refer to rclone version including patches

hosts/azure/jenkins-controller/configuration.nix
Required for parallel building
=> Add nix-eval-jobs to jenkins path

hosts/testagent-dev/configuration.nix
Run one agent for each hardware test device connected to the testagent-dev machine. This enables future work for running the tests in parallel by utilizing different nodes (jenkins side still in progress).
=> Run multiple Jenkins agent services simultaneously

hosts/azure/binary-cache/configuration.nix, hosts/azure/jenkins-controller/configuration.nix
Add RequiresMountsFor=/var/lib/jenkins to jenkins-config.service.
There's no point starting this before /var/lib/jenkins is mounted, as we read the admin password from there to interact with the jenkins API.
=> az-jenkins-controller: jenkins-config needs mount

hosts/azure/binary-cache/configuration.nix, hosts/azure/jenkins-controller/configuration.nix
This option defaults to true, but we disable the admin API.
When manually copying new system closures and activating them (for testing purposes), this causes the activation to hang.
=> hosts/azure: explicitly disable caddy reloads

scripts/add-remote-user.sh
- Don't explicitly set the group for the new user
- Support command-line argument `-v`
- Pretty-print errors
=> scripts: Fixes to add-remote-user

nix/devshell.nix
wget is assumed to be installed when running `scripts/get-artifacts.sh`:
```
Error: command 'wget' is not installed (Hint: are you inside a nix-shell?)
```
but wget is not actually part of the devshell.
=> Add wget to devshell

terraform/modules/azurerm-nix-vm-image/main.tf
Increase image blob storage timeouts that were not increased by: https://github.com/tiiuae/ghaf-infra/pull/220
See: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_blob#timeouts
=> Increase image storage timeouts

terraform/jenkins-controller.tf, terraform/main.tf
- auto add jenkins controller to KV policy
=> Add KV policy management

hosts/agents-common.nix, hosts/azure/jenkins-controller/jenkins-casc.yaml, hosts/testagent-dev/configuration.nix, hosts/testagent/configuration.nix
Greatly simplifies the setup of testing environment or moving it to a different controller.
After this change, all you need to do to connect the test setup to a jenkins environment is to supply the controller url and admin password in `/var/lib/jenkins/jenkins.env`, and (re)start `setup-agents.service`. This service will then start the hardware agents.
Agent services creation moved to a separate file so it can be imported from all testagent configurations.
=> Automate creation of HW test nodes and fetching of secrets

hosts/azure/jenkins-controller/configuration.nix
Jenkins Job Builder sets the `concurrent=false` by default. We need to set it to `true` by default to match the Jenkins default and to allow parallel pipelines.
On pipelines that should not run in parallel, we already explicitly set the `disableConcurrentBuilds()` in the declarative pipeline properties.
Reference:
https://jenkins-job-builder.readthedocs.io/en/latest/definition.html
=> jenkins-controller: Set job concurrency enabled

hosts/azure/jenkins-controller/configuration.nix
Retry post-build-hook upload three times at 10 second interval before giving up.
Before this change, it would retry two times. However, there have been some cases where the upload failed the second time also which would fail the build before this change.
=> Increase post-build upload attempts

hosts/builders/build3/configuration.nix, hosts/builders/build4/configuration.nix, hosts/builders/developers.nix, hosts/builders/hetzarm/configuration.nix, users/default.nix, users/github.nix
- Cleanup build4 configuration: remove `nginx` and obsolete yubikey `signer` configurations which are no longer needed on build4.
- Move `user-github` out of `developers.nix`: explicitly import `user-github` on hosts that may be used from github actions.
- We need to keep `github-user` on build3 until all curent github actions are changed to start using build4 as their remote builder. Currently, build3 is still used as a remote builder from [ghaf](https://github.com/tiiuae/ghaf/blob/285596115982fd3eb53ebd358b1dbcc3c5128414/.github/workflows/build.yml#L161) and [ghaf-infra](https://github.com/tiiuae/ghaf-infra/blob/da8a2c6ed8c534d54217c4e99cd97febf4eb5f75/.github/workflows/test-ghaf-infra.yml#L114-L115).
=> Enable GitHub builds on build4

hosts/builders/build3/configuration.nix, hosts/builders/build4/configuration.nix, hosts/builders/developers.nix, hosts/builders/hetzarm/configuration.nix, terraform/main.tf, users/default.nix, users/remote-build.nix
- Move user-remote-build out of developers.nix: explicitly import user-remote-build on hosts that may be used from Azure jenkins-controller initiated 'external' builds.
- Start using `remote-build@build4.vedenemo.dev` as external x86 builder from jenkins-controller
- We need to keep remote-build user on build3 until all currently deployed ghaf-infra jenkins-controller instances that make use of external builders, have been migrated to a version of ghaf-infra including the changes from this PR.
=> Start using build4 as x86 external builder in Azure infra

.github/workflows/test-ghaf-infra.yml, hosts/common.nix, scripts/test-nix-cache.sh
- Remove ghaf-infra references to decommissioned cache `cache.vedenemo.dev`, replacing it with `prod-cache.vedenemo.dev`
- Remove cache `cache.ssrcdevops.tii.ae`, which we should not need in our builders
- Start using `build4` as a x86 remote builder from the `test-ghaf-infra.yml` workflow
- This PR does not remove the nix configuration for [cache.vedenemo.dev](https://github.com/tiiuae/ghaf-infra/blob/c54a784f4819be6343d9cdbf54e2aaba3b7c381b/hosts/binarycache/configuration.nix#L62). This should be removed in a follow-up, together with re-purposing the current `cache.vedenemo.dev` host.
The change to github action was tested in a fork: https://github.com/henrirosten/ghaf-infra/pull/3.
=> Remove cache.vedenemo.dev usage

terraform/README.md, terraform/builder.tf
- Do not upload x86 builder vhd image to azure if the infrastructure will not create the x86 builder VM.
- Add instructions to terrafrom/README.md to work around an azurerm issue this change exposes.
=> Skip x86 builder image unless builder VMs are created

terraform/main.tf
We can not automatically assign alternative names per environment type since we support having potentially many environments of the same type. Otherwise we might end-up deploying, say, two 'dev' type instances that both claim ownership of domain name 'dev-cache.vedenemo.dev'. Such alternative names need to be manually configured for each instance (once) in the relevant host's caddy config at `/var/lib/caddy/caddy.env`, setting the SITE_ADDRESS accordingly.
=> terraform: Stop assigning vedenemo domain names

scripts/connect-testagent.sh
Added a new script with basic structure copied from `add-remote-user.sh`. This script automates the task of connecting testagent with a given jenkins controller, making it even easier to spin up ephemeral builds.
It opens an ssh connection to the jenkins controller to copy it's details, then supplies them to the testagent and restarts the systemd service.
=> Add script to connect testagent with controller

flake.lock
Update to the newest versions of `sbomnix`, `ci-yubi` and `robot-framework`
=> Update flake inputs of pipeline dependencies

.sops.yaml, hosts/testagent/agents-common.nix, hosts/testagent/credentials.yaml
Adds new encrypted secret file `credentials.yaml` which is imported by all of the testagent machines. It contains the secrets that are currently manually configured into jenkins controller.
After this change, the ghaf-robot tests need to be updated to actually read these secrets from `/run/secrets/`, only then can these credentials be removed from the jenkins side.
=> Make test credentials available on the testagents

terraform/arm-builder.tf, terraform/binary-cache.tf, terraform/builder.tf, terraform/jenkins-controller.tf, terraform/main.tf, terraform/persistent/binary-cache-sigkey/binary-cache-sigkey.tf, terraform/persistent/resources/main.tf, terraform/terraform-init.sh, terraform/test-deployment.sh
- Store nix trusted public key in persistent storage
- Read the public key from the persistent storage instead of hard-coding the expected value in the terraform main module
- Change `test-deployment.sh` to support changed configuration: expected trusted public key values for eun location are pre-defined in the script - it also now supports providing the trusted public key from the command line with a new option `-p`
=> Nix trusted public key in persistent

.sops.yaml, hosts/binarycache/configuration.nix, hosts/builders/build3/configuration.nix, hosts/builders/build4/configuration.nix, hosts/builders/ficolo.nix, hosts/builders/hetzarm/configuration.nix, hosts/builders/hetzarm/secrets.yaml, hosts/ficolo-common.nix, hosts/ghaf-log/configuration.nix, hosts/ghaf-log/secrets.yaml, hosts/ghaf-proxy/configuration.nix, hosts/ghaf-proxy/secrets.yaml, hosts/himalia/configuration.nix, hosts/monitoring/configuration.nix, hosts/monitoring/secrets.yaml, services/monitoring/default.nix
- Monitoring server now available at https://monitoring.vedenemo.dev
- Anonymous access removed, needs grafana account to log in
- Loki api endpoint has basic auth, except when used from within ficolo internal network
- New options added to monitoring module
- Hetzner servers can now push logs by using basic auth password
=> Monitor logs from external servers

terraform/persistent/binary-cache-sigkey/binary-cache-sigkey.tf, terraform/persistent/builder-ssh-key/builder-ssh-key.tf, terraform/persistent/main.tf, terraform/persistent/resources/main.tf
Stop using hard-coded `TerraformAdminsGHAFInfra` group `object_id`, replacing it with `azurerm_client_config.current.object_id`.
=> Stop using TerraformAdminsGHAFInfra group

.github/workflows/test-ghaf-infra.yml, flake.lock, flake.nix, nix/checks.nix, nix/devshell.nix, scripts/nix-fast-build.sh, tasks.py
- Move pycodestyle, pylint, black, and format checks from `task.py` to ghaf-infra flake `.#checks`
- Remove all redundant checks from `task.py`
- Introduce `nix-fast-build.sh` helper to run relevant flake builds with [nix-fast-build](https://github.com/Mic92/nix-fast-build) to execute all evaluation/build operations completely on the remote builder. Add relevant dependencies to nix `devshell`.
- Start using `nix-fast-build.sh` from github action workflow `test-ghaf-infra.yml`: run all checks and build relevant x86 and aarch targets on remote. This adds some new checks too: the workflow now also builds all azure nixosConfigurations, as well as runs the `.#checks` on aarch64.
Note: after this change, cachix cache on the `test-ghaf-infra.yml` workflow  is used only to cache the ghaf-infra …
=>  Start using nix-fast-build in github action CI

scripts/get-artifacts.sh
- Use wget `--continue` option to resume downloading a partially downloaded remote directory. 
- We also need to use `--no-if-modified-since`, because otherwise wget would consider a partially downloaded file a complete due to `--timestamping`
After these changes, one can abort `get-artifacts.sh` (e.g. with ctrl-c) and continue the download later - the script will resume the download as long as the output directory from the earlier attempt is not removed.
=> get-artifacts.sh: Fix resume download

terraform/main.tf, terraform/persistent/builder-ssh-key/builder-ssh-key.tf, terraform/persistent/resources/main.tf
Create and use per-environment builder ssh key unless external builders are used in the given ghaf-infra instance. Builder ssh key used to access the external builder(s) is still stored and accessed from the persistent resource group.
After this change, ghaf-infra configurations that don't use external builders (e.g. 'release') will create and use new builder ssh-keys on every new ghaf-infra deployment.
=> Support per-environment builder ssh keys

terraform/README.md, terraform/terraform-init.sh
Add `terraform-init-sh` option `-d` to allow destroying ghaf-infra workspace and workspace-specific persistent.
=> terraform-init.sh: Support deleting workspace

hosts/monitoring/configuration.nix
Alerts for cache.vedenemo.dev should be disabled. It's shut down
=> Disable the monitoring cache.vedenemo.dev

terraform/binary-cache.tf, terraform/builder.tf, terraform/jenkins-controller.tf, terraform/main.tf, terraform/modules/azurerm-nix-vm-image/main.tf
This is an attempt to fix the occasional errors that occur on clean deployments. An example terraform error from a deployment before the changes from this PR below:
```
│ Error: creating Blob "binary-cache.vhd" (Container "ghaf-infra-vm-images" / Account "imgreleaseeun"): creating storage blob
on Azure: while uploading source file "/nix/store/dvg2fqgxzd116zjhw9c5bbps96bzsfqi-azure-image/disk.vhd": writing page at 
offset 4455006208 for file "/nix/store/dvg2fqgxzd116zjhw9c5bbps96bzsfqi-azure-image/disk.vhd": 
blobs.Client#PutPageUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned 
an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of 
Authorization header is formed …
```
=> terraform: Fix random VM image deployment errors

hosts/testagent/release/configuration.nix
Update release testagent's usb_sd_mux_port value
after mux changed to newer version.
=> Update release agent's usb_sd_mux_port

flake.lock, flake.nix, hosts/azure/jenkins-controller/configuration.nix, hosts/common.nix, pkgs/coverity/default.nix, services/rclone-http/default.nix
- `jenkins-job-builder` is currently broken, so using the old version for now. Issue has been filed: https://github.com/NixOS/nixpkgs/issues/362054 and fix is coming.
- rclone 1.68.2 breaks our pipelines, archival step results in an error (path truncated):
```
2024/12/09 12:39:45 CRITICAL: Failed to create file system for ":webdav:/ghaf-main-pipeline/build_5-commit_...": 
read metadata failed: 308 Permanent Redirect
```
Reverting to 1.66 with our webdav patches fixes the issue, but this should be looked into @flokli 
- Migration steps for azure environment: run `./terraform-init -w` again before applying.
=> Update infra to NixOS 24.11

.reuse/dep5, REUSE.toml
Reuse dep5 is [deprecated](https://reuse.software/spec-3.2/#dep5-deprecated): replace reuse dep5 with [REUSE.toml](https://reuse.software/spec-3.2/#reusetoml)
=> Replace reuse dep5 with REUSE.toml

hosts/testagent/dev/configuration.nix, hosts/testagent/prod/configuration.nix
We are connecting power measurement system to lenovo-x1 on prod setup. Already tested it in dev setup. So to make it work only in prod setup need to have that rpi ip config moved to prod.
=> Move rpi config from dev to prod

hosts/azure-common.nix, terraform/jenkins-controller.tf
Use membership in the "wheel" group to control whether users are allowed to sudo or not, rather than managing it explicitly.
Also configure everyone in the wheel group to be a trusted Nix user. These same users where already able to sudo without password, so this doesn't give them more privileges.
However, it allows them to also use nix-copy-closure to upload loacally-built closures to a system, which is a great way to incrementally test changes without having to recreate a new VM image every time.
A subsequent terraform run would still redeploy a new VM with a new image, but this can dramatically reduce the iteration time during development.
=> hosts/azure: add users to wheel, make trusted

flake.lock, hosts/azure/jenkins-controller/configuration.nix, hosts/builders/build3/configuration.nix, hosts/monitoring/configuration.nix, pkgs/coverity/default.nix
- Jenkins is updated to fix a CVE https://github.com/NixOS/nixpkgs/pull/360869 and also for better plugin compability
- jenkins-job-builder is now fixed so we don't have to use the 24.05 version.
- Coverity had a hash mismatch -> updated hash.
- Most recent nix formatter behaves slightly differently so had to do a reformat.
=> Flake update

terraform/binary-cache.tf
Marko getting the
```
Error: Invalid index
│
│   on binary-cache.tf line 37, in module "binary_cache_vm":
│   37:         ssh_authorized_keys = local.ssh_keys[user]
│     ├────────────────
│     │ local.ssh_keys is object with 12 attributes
```
=>  Fix typo ctsopokis in binary-cache

REUSE.toml, flake.lock, flake.nix, hosts/azure/jenkins-controller/configuration.nix, hosts/azure/jenkins-controller/jenkins-casc.yaml, hosts/azure/jenkins-controller/plugins.nix, hosts/azure/jenkins-controller/plugins.toml, hosts/azure/jenkins-controller/prefetch-plugins.sh, nix/devshell.nix, nix/treefmt.nix
- `jenkinsPlugins2nix` is used to generate a set of jenkins plugins to install, complete with pinned versions and hashes.
- Installed `lockable-resources` plugin so we can lock resources in pipelines.
- Jenkins CASC changes
- Removed default values, only keeping what we actually change. This makes it much more readable.
- timestamper plugin configured to enable timestamps in every job.
- pipeline graph now shows up on build page without extra clicking.
- more executors.
=> Jenkins plugin setup improvements

flake.lock, flake.nix
This change fixes an issue with vulnix scans, an example error is here: https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-nightly-pipeline/62/execution/node/385/log/.
That same issue was fixed in vulnix upstream: https://github.com/nix-community/vulnix/pull/101. The vulnix fix in nixpkgs [has not been backported to 24.11](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/vu/vulnix/package.nix), which is the nixpkgs version ghaf-infra flake [currently follows](https://github.com/tiiuae/ghaf-infra/blob/bfef20ce4a387ef67c40bc00326ad45ba0feab76/flake.nix#L8). Therefore, if we enforce sbomnix to follow the 24.11 nixpkgs, it will use vulnix version `vulnix-1.10.1-unstable-2024-04-02` which does not include the fix.
To include the fix in ghaf-infra, we …
=> sbomnix: Use nixpkgs from sbomnix upstream

hosts/monitoring/configuration.nix, hosts/monitoring/secrets.yaml
Users can now log in to https://monitoring.vedenemo.dev with their Github account if they are in the `tiiuae` org and in the `devenv-fi` team.
=> Use Github auth for monitoring server access

hosts/testagent/dev/configuration.nix, hosts/testagent/prod/configuration.nix, hosts/testagent/release/configuration.nix
Orin AGX has 12 threads available in all of the 3 setups: dev, prod and release but only 8 was configured for multi- thread performance tests.
=> Set correct thread number for Orin AGX

hosts/azure/jenkins-controller/jenkins-casc.yaml
Allows locking the sbom stage to not run in parallel
=> Add SBOM locked resource

hosts/builders/builders-common.nix
Increase the maximum number of open files per user, see `ulimit -n`.
Fixes an issue that we have occasionally started seeing on builders:
```
error: creating pipe: Too many open files
```
=> builders: Increase ulimit -n

README.md, docs/tasks.md, hosts/testagent/prod/configuration.nix, nix/deployments.nix, nix/devshell.nix, tasks.py
- Deploy function is removed from `tasks.py`, as deploy-rs is supposed to be used.
- `tasks.py` now evaluates a nix expression that gets all target data from `nix/deployments.nix`, avoiding the need to keep two separate lists in sync.
- Updated docs to remove mentions of `tasks.py` deploy.
- Use nixos-anywhere from devshell instead of hardcoded sha.
=> Populate task targets from deploy-rs node data

hosts/azure/jenkins-controller/jenkins-casc.yaml, hosts/testagent/agent.nix, hosts/testagent/agents-common.nix, hosts/testagent/dev/configuration.nix, hosts/testagent/prod/configuration.nix, hosts/testagent/release/configuration.nix, hosts/testagent/uae-dev/configuration.nix
Adds all three testsets as nodes to each controller (dev, prod and release). Any combination of these can connect. Builds can use both at the same time with the device label.
Refactored testagents config to be more consistent, and moved the agent connection script to its own module with an option.
=> Allow using more than one testagent per controller

hosts/azure-common.nix
Enable [zramSwap](https://search.nixos.org/options?show=zramSwap.enable) on all Azure hosts to try to mitigate the OOM issues we have started seeing recently, especially on jenkins-controller.
=> azure-common: Enable zramSwap in all Azure hosts

tasks.py
Fix the `install` task which, before this PR, failed after kexec switch as follows:
```
error: flake 'git+file:///.../ghaf-infra' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."
{target.nixosconfig}".config.system.build.diskoScript', 'legacyPackages.x86_64-linux.nixosConfigurations.
"{target.nixosconfig}".config.system.build.diskoScript' or 'nixosConfigurations."{target.nixosconfig}".config.system.build.diskoScript'
```
=> task.py: Fix inv install

hosts/testagent/dev/configuration.nix, hosts/testagent/prod/configuration.nix
Access to prod and dev agents would allow me to bind test agents back to prod/dev after a release build
=> Add ktu to dev and prod test agents

hosts/testagent/agent.nix, hosts/testagent/dev/configuration.nix, hosts/testagent/prod/configuration.nix, hosts/testagent/release/configuration.nix, hosts/testagent/uae-dev/configuration.nix
Release set doesn't have dell-7330 at the moment. Add config option to set the hardware for different testagents.
=> Allow testagents to have different hardware

.sops.yaml, hosts/builders/build1/configuration.nix, hosts/builders/build1/secrets.yaml, hosts/builders/build2/configuration.nix, hosts/builders/build2/secrets.yaml, hosts/builders/hetzarm/configuration.nix, hosts/builders/hetzarm/secrets.yaml
Main changes:
- Add host keys to `build1` and `build2`
- Add [cachix-watch-store service](https://search.nixos.org/options?channel=unstable&show=services.cachix-watch-store.enable&from=0&size=50&sort=relevance&type=packages&query=cachix-watch-store) and cachix authentication token for hosts `build1` and `hetzarm` to start populating [ghaf-dev](https://app.cachix.org/organization/tiiuae/cache/ghaf-dev) cachix cache
After this PR is deployed, `cachix-watch-store` service on hosts `build1` and `hetzarm` starts pushing all newly built nix store paths to cache https://ghaf-dev.cachix.org. If this turns out to be too much, we might later want to limit the pushes, but I'd propose we start with this.
=> Add cachix-watch-store to build1 and hetzarm

terraform/main.tf
Reduce the virtual machine size of the dev binary cache from 4 vCPU to 2 vCPU  to save costs. Also, move from d3 virtual machine family to d4 because d3 is a previous generation series. While older VM sizes are supported until further notice, Azure recommends using newer generations for improved performance and security.
=> Reduce dev binary cache vm size to save costs

.github/workflows/authorize.yml, .github/workflows/test-ghaf-infra.yml, .github/workflows/warn-on-workflow-changes.yml, flake.nix, scripts/nix-fast-build.sh
- Authorize pre-merge workflow runs based on author's membership in tiiuae organization, separating the `authorization.yml` to its own workflow
- Move the workflow changed warning to `warn-on-workflow-changes.yml` which can trigger on `pull_request` rather than `pull_request_target`
- Builds are now run on `build1` and `hetzarm`, both of which push to cachix cache
- Add nix substituters configuration to `flake.nix` - trust our own cachix cache 
- Start using ssh-agent for the builder ssh key in the pre-merge action
- Start building x86 devShell in the pre-merge action to have the devshell dependencies also available in the cachix cache
These changes have been tested in fork at https://github.com/henrirosten/ghaf-infra/actions/runs/14620192422
=> Align pre-merge workflow with Ghaf

.github/workflows/actions-security-analysis.yml
[zizmor](https://woodruffw.github.io/zizmor/) is a static analysis tool for GitHub Actions to find common security issues.
Adds a workflow to run zizmor on push and pull request. The findings will be available in the repository security tab, similarly to the currently used scorecard workflow.
Note: https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
> zizmor will always exit with code 0 even if findings are present, unless an internal error occurs during the audit.
> workflow itself will always succeed, resulting in a green checkmark in GitHub Actions. This should not be confused with a lack of findings.
=> GitHub actions security analysis

hosts/common.nix
Now you can always tell which commit hash of ghaf-infra a given host was deployed from by running:
```sh
nixos-version --configuration-revision
```
=> Store information about configuration revision into hosts

hosts/hetztest/casc/jenkins-casc.yaml, hosts/hetztest/configuration.nix, hosts/hetztest/plugins.json, hosts/hetztest/secrets.yaml
- Allow triggering hetztest jenkins pipelines with api token and `api_user` user
- Configure `api_user` with casc
- Store api token in sops; configure the token on jenkins with casc
- Trigger (all) pipelines every time the jenkins service (re)starts
- Update hetztest jenkins plugins
=> hetztest: Allow pipeline trigger with api token

.github/workflows/test-ghaf-infra.yml, nix/devshell.nix, scripts/nix-fast-build.sh
Allow specifying `nix-fast-build.sh` build targets with regex filter via option `-f`. This change makes the script more generic, making it possible to use the `nix-fast-build.sh` to build any standard nix flake. As a result, we can remove the [static list](https://github.com/tiiuae/ghaf-infra/blob/e83a89737a402494e2f24917ce780edb1bb18f59/scripts/nix-fast-build.sh#L140-L156) of ghaf-infra specific build targets: from now on, the list of targets we build in the `test-ghaf-infra.yml` workflow automatically updates based on the [target filters](https://github.com/tiiuae/ghaf-infra/blob/c040d281dcec156f6030d2edfebaaf65353c1d95/.github/workflows/test-ghaf-infra.yml#L83-L86) specified in the workflow and nixosConfigurations in the ghaf-infra flake. 
These changes have been tested in a fork at: …
=> Improve nix-fast-build.sh

.sops.yaml, hosts/builders/build1/secrets.yaml, hosts/builders/build2/configuration.nix, hosts/builders/build2/secrets.yaml, hosts/builders/build3/secrets.yaml, hosts/builders/build4/configuration.nix, hosts/builders/build4/secrets.yaml
This PR adds fayad to the list of users who can decrypt builder secrets, and also fixes some issues with missing secret definitions on build4 and build2
=> Allow fayad access to builder secrets

hosts/monitoring/configuration.nix, hosts/monitoring/secrets.yaml, hosts/testagent/dev/configuration.nix, hosts/testagent/dev/secrets.yaml, hosts/testagent/prod/configuration.nix, hosts/testagent/prod/secrets.yaml, hosts/testagent/release/configuration.nix, hosts/testagent/release/secrets.yaml
Adds pushgateway to monitoring server under `/push/` with basic auth. This can be used to push metrics from inaccessible servers (testagents).
The actual metrics are to be implemented later, this only adds the capabilities.
=> Add prometheus pushgateway to accept metrics from testagents

hosts/testagent/dev/configuration.nix, hosts/testagent/prod/configuration.nix, hosts/testagent/release/configuration.nix, hosts/testagent/uae-dev/configuration.nix
Add UDEV rules for SSD-drives that are used
with test devices and add those links to device
configurations.
=> Add UDEV rules for SSD-drives

flake.lock, flake.nix, hosts/testagent/agents-common.nix
Adds the newly packaged KMTronic scripts into testagents PATH as `kmtronic-control` and `kmtronic-status`
=> Install KMTronic relay scripts to testagents

hosts/builders/ficolo.nix
Ficolo x86 remote builders are working long time with only 8 cores resulting long build times. Trying to improve performance by setting cores to 24 and reducing maxjobs to 16. This combo could still reach peak load of 384.
=> Set Ficolo builder cores to 24, maxjobs to 16

.sops.yaml, hosts/default.nix, hosts/ghaf-auth/configuration.nix, hosts/hetzci-dev/casc/jenkins-casc.yaml, hosts/hetzci-dev/casc/pipelines/ghaf-demo-manual.groovy, hosts/hetzci-dev/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci-dev/casc/pipelines/modules/utils.groovy, hosts/hetzci-dev/configuration.nix, hosts/hetzci-dev/disk-config.nix, hosts/hetzci-dev/plugins.json, hosts/hetzci-dev/plugins.txt, hosts/hetzci-dev/purge-jenkins-artifacts.sh, hosts/hetzci-dev/secrets.yaml, nix/deployments.nix, nix/devshell.nix
Add configuration for https://hetzci-dev.vedenemo.dev/ - Jenkins dev host on hetzner.
Configuration is copied from hetzci-prod with minor changes to relevant configuration options. We want to keep the dev config separate from `prod` to allow testing configuration changes on `dev` fully independent of `prod`.
=> hetzci-dev: Initial configuration

hosts/common.nix
Stop using the (to-be-retired) 'prod-cache.vedenemo.dev' substituter
=> hosts/common.nix: Stop using prod-cache.vedenemo.dev

README.md, hosts/builders/hetz86-1/configuration.nix, hosts/builders/hetz86-1/secrets.yaml, hosts/hetzci-dev/configuration.nix, hosts/hetzci-prod/configuration.nix
- Stop using ficolo builders in hetzci, instead, use hetz86-1 builder
- Enable cachix-watch-store service in hetz86-1
- Update README.md with latest host overview
=> Hetzner CI and builder updates

hosts/hetzci/dev/configuration.nix, hosts/hetzci/prod/configuration.nix, hosts/hetzci/vm/configuration.nix
Set Jenkins home directory (currently at `/var/lib/jenkins`) mode to 755. This does not change the current mode, just states it explicitly to avoid possible issues in case it later changes for one reason or another.
=> hetzci: Set jenkins home mode

hosts/hetzci/dev/casc/jenkins-casc.yaml, hosts/hetzci/dev/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/prod/casc/jenkins-casc.yaml, hosts/hetzci/prod/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/vm/casc/jenkins-casc.yaml, hosts/hetzci/vm/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly.groovy
- Add pipeline 'ghaf-nightly-perftest' with same functionality as [ghaf-perftest-pipeline](https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/main/ghaf-perftest-pipeline.groovy) in the Azure jenkins pipelines
- Retain build logs from nightly triggered pipelines from the last 30 builds instead of 10
- Add 'orin-agx-64' node removing 'nuc' and support for related HW tests, bringing hetzci on-par with Azure with this respect. Ref: [PR#453](https://github.com/tiiuae/ghaf-infra/pull/453), Azure [ghaf-hw-test](https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/6c4fa3fa02a0ecb26953765ce197d68bb4558d2b/ghaf-hw-test.groovy#L200-L209) and [nightly](https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/6c4fa3fa02a0ecb26953765ce197d68bb4558d2b/ghaf-nightly-pipeline.groovy#L131) pipelines.
- Remove …
=> hetzci: Run perf test nightly

hosts/hetzci/README.md, hosts/hetzci/dev/casc/pipelines/ghaf-main.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-pre-merge-manual.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-pre-merge.groovy, hosts/hetzci/dev/casc/pipelines/modules/utils.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-pre-merge-manual.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-pre-merge.groovy, hosts/hetzci/prod/casc/pipelines/modules/utils.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-pre-merge-manual.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-pre-merge.groovy, hosts/hetzci/vm/casc/pipelines/modules/utils.groovy
- Make all pipelines available in all Hetzner environments as requested by @milva-unikie, @azbeleva  and @leivos-unikie. However, I assume we don't want to auto-trigger nightly pipelines both in `prod` and `dev`, therefore this PR disables the cron trigger in nightly pipelines on `dev`
- Move the `setBuildStatus` function to `utils.groovy` now that it is used by many pipelines
- Retain 50 latest ghaf-pre-merge pipeline Jenkins build logs instead of 10
- Update README to match the changes from this PR
These changes have been deployed both to [dev](https://ci-dev.vedenemo.dev/) and [prod](https://ci-prod.vedenemo.dev/) already
=> hetzci: Same pipelines in all environments

hosts/hetzci/dev/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-manual.groovy
Fix a mix-up in ghaf-manual pipeline: we have no test hardware for dell-latitude-7230-debug so we should not execute any tests for it. Instead, tests should be executed for dell-latitude-7330-debug.
=> hetzci: Fix dell tests in ghaf-manual pipeline

hosts/hetzci/dev/casc/pipelines/modules/utils.groovy, hosts/hetzci/prod/casc/pipelines/modules/utils.groovy, hosts/hetzci/vm/casc/pipelines/modules/utils.groovy
This is another fix for the same issue discussed earlier at: https://github.com/tiiuae/ghaf-infra/pull/509:
- `sync` should not be needed with `mkdir -p`
- What happens is, if there's delay between when the local artifact directory is created and when it's used, `jenkins-purge-artifacts` service removes the directory as if it was no longer needed. Moving the `mkdir` to the same shell command where the directory is used gets rid of this problem.
=> hetzci: Fix missing artifacts directory

hosts/hetzci/dev/configuration.nix, hosts/hetzci/dev/secrets.yaml, hosts/hetzci/prod/configuration.nix, hosts/hetzci/prod/secrets.yaml, hosts/monitoring/configuration.nix
- Monitor metrics of `hetzci-dev` and `hetzci-prod` through sshified. Also send logs to Loki.
- Stop monitoring `prod-cache.vedenemo.dev`
Currently these changes are deployed to monitoring server and ci-dev
=> Start monitoring hetzci-dev and -prod

hosts/hetzci/dev/casc/pipelines/ghaf-nightly-poweroff.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly-poweroff.groovy
Adapt [turn-off-test-devices.groovy](https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/main/turn-off-test-devices.groovy) to Hetzner `vm` and `dev` environments.
Deployed and tested in dev: https://ci-dev.vedenemo.dev/job/ghaf-nightly-poweroff/
=> hetzci: Adapt poweroff pipeline from Azure Jenkins

hosts/hetzci/dev/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly.groovy
Added installation and wiping pipeline steps for ghaf-installer image, for now only for nightly tests.
Ghaf-intaller build: https://ci-dev.vedenemo.dev/job/ghaf-hw-test/88/
Successful normal Ghaf build after that: https://ci-dev.vedenemo.dev/job/ghaf-hw-test/89/
=> Add ghaf-installer testing

hosts/hetzci/dev/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/dev/casc/pipelines/modules/utils.groovy, hosts/hetzci/dev/configuration.nix, hosts/hetzci/prod/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/prod/casc/pipelines/modules/utils.groovy, hosts/hetzci/prod/configuration.nix, hosts/hetzci/vm/casc/pipelines/ghaf-hw-test.groovy, hosts/hetzci/vm/casc/pipelines/modules/utils.groovy, hosts/hetzci/vm/configuration.nix
- Add provenance file generation to all hetzci pipelines for `vm`, `dev` and `prod` environments.
- Add a placeholder step in ghaf-hw-test pipeline to verify the provenance. We can't properly verify the provenance yet, since we don't sign the provenance in hetzci as of now. Generating signature for the provenance (and other important build results) will be implemented in a follow-up PR, at which point the provenance verification step added in this PR should also be modified accordingly.
Example run in dev: https://ci-dev.vedenemo.dev/job/ghaf-main/22/ (see the 'scs' directory in 'Artifacts').
Example provenance file from that run, e.g.: https://ci-dev.vedenemo.dev/artifacts/ghaf-main/20250714_095103000-commit_60b5fb785178ac0243b8ee2083878c847ee4b08d/scs/packages.aarch64-linux.nvidia-jetson …
=> hetzci: Add provenance generation to all pipelines

flake.lock, hosts/common.nix
- Update to latest from nixos/nixpkgs/nixos-25.05
- Use latest version of `nix` (currently 2.28.4 in nixos-25.05)
=> Update nixpkgs input

hosts/ghaf-auth/configuration.nix, terraform/jenkins-controller.tf
- Separate northeurope and uae envs under a different client IDs, with combined workspaces under them (requires redeploy of azure envs).
- Change the name that displays in the oauth dialog from `hetzci-prod` to `ci-prod.vedenemo.dev`. (and same for dev)
- Use more variables when values are repeated.
=> Refactor auth clients

hosts/hetzci/dev/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly-perftest.groovy
This PR changes the perftest pipeline so all the targets run sequentially instead of parallel.
The change was requested by the test team because perftest results are apparently not reliable when multiple performance tests are executed at the same time.
Tested in dev: https://ci-dev.vedenemo.dev/job/ghaf-nightly-perftest/36/
=> hetzci: Run perftest sequentially

hosts/hetzci/dev/casc/jenkins-casc.yaml, hosts/hetzci/dev/plugins.json, hosts/hetzci/dev/plugins.txt, hosts/hetzci/prod/casc/jenkins-casc.yaml, hosts/hetzci/prod/plugins.json, hosts/hetzci/prod/plugins.txt, hosts/hetzci/vm/casc/jenkins-casc.yaml, hosts/hetzci/vm/plugins.json, hosts/hetzci/vm/plugins.txt
Updated Jenkins plugins and added `dark-theme` plugin. Now Jenkins follows your system's dark mode setting.
=> Enable dark theme for Jenkins

hosts/ghaf-auth/configuration.nix, hosts/hetzci/dev/configuration.nix, hosts/hetzci/prod/configuration.nix, hosts/hetzci/vm/configuration.nix
- Skip provider button, makes logging in one click instead of two. We only have one provider (ghaf-auth/dex) so it's not useful.
- Request `offline_access` scope and grant `refresh_token` to clients, enabling the ability to refresh sessions. These tokens are valid for a week. The outcome of this changes is that you should not have to relogin to ci-dev and ci-prod so frequently anymore. Your session should be remembered for a week.
- Enable dark mode css
=> Enable the use of refresh tokens to keep auth session alive

hosts/hetzci/dev/casc/pipelines/ghaf-main.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-main.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-main.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly.groovy
Add target `system76-darp11-b-debug` to vm, dev and prod pipelines: main, manual and nightly.
Tested [here](https://ci-dev.vedenemo.dev/job/ghaf-main/39/) and [here](https://ci-dev.vedenemo.dev/job/ghaf-manual/60/).
=> hetzci: Add system76-darp11-b-debug targets

nix/deployments.nix, tasks.py
Everything under `flake.deploy` gets evaluated during deploy, even though `deploy.targets` was only there for `tasks.py` to use. Because `deploy.targets` checks for the presence of secrets, it has to evaluate the host's config.
Moved targets out of deploy and added a new top-level flake output `.#installationTargets`. Now only the host that is being deployed gets evaluated when you run `deploy`, speeding up the process significantly.
=> Stop evaluating every host on deploy

hosts/ghaf-monitoring/provision/alert-rules.yaml, hosts/hetzci/release/configuration.nix
- ci-release: Move caddy state to peristent volume so we don't hit the Let's Encrypt TLS rate limits when ci-release Jenkins controller host gets re-installed for ephemeral builds.
- ghaf-monitoring: Improve disk space alert to fire if disk usage on an ext4 disk is greater than 98%. This is needed to not fire on small disks (such as caddy state) based on absolute GB limit.
Tested and currently deployed to [monitoring.vedenemo.dev](https://monitoring.vedenemo.dev/alerting/grafana/beuvsalzfeigwe/view) and https://ci-release.vedenemo.dev/
=> hetzci-release: Move caddy state to persistent volume

hosts/hetzci/dev/casc/pipelines/modules/utils.groovy, hosts/hetzci/prod/casc/pipelines/modules/utils.groovy, hosts/hetzci/release/casc/pipelines/modules/utils.groovy, hosts/hetzci/vm/casc/pipelines/modules/utils.groovy
Add nix build option `--fallback` to fall back on building the derivation locally (on the confgured remote builders in hetzci config) if realizing the output paths through the substitutes fails. This is a workaround to recent cachix 'Cannot serve NAR' [issue that occurs on some paths](https://ci-prod.vedenemo.dev/job/ghaf-pre-merge/220/pipeline-overview/log?nodeId=110).
=> hetzci: nix build with fallback on jenkins pipelines

hosts/hetzci/dev/configuration.nix, hosts/hetzci/prod/configuration.nix, hosts/hetzci/release/configuration.nix, hosts/hetzci/vm/configuration.nix
I notice oauth2-proxy occasionally fails after new installation, which I've been testing on release environment lately.
This PR changes the oauth2-proxy service restart config so it doens't fail on fresh installations.
=> hetzci: Change oauth2-proxy restart config

hosts/builders/cachix-push.nix, hosts/builders/cachix-push.sh, hosts/builders/hetz86-rel-1/configuration.nix, hosts/builders/hetz86-rel-1/secrets.yaml, hosts/builders/hetzarm-rel-1/configuration.nix, hosts/builders/hetzarm-rel-1/secrets.yaml, hosts/hetzci/release/casc/pipelines/ghaf-release.groovy
- Add `cachix-push.nix` nix module which implements a systemd service that is functionally-wise similar to [cachix-watch-store](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/system/cachix-watch-store.nix), but allows filtering the store paths pushed to cachix. This service can be used to replace the [cachix-watch-store](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/system/cachix-watch-store.nix) service (which we currently use e.g. in [hetzarm](https://github.com/tiiuae/ghaf-infra/blob/main/hosts/builders/hetzarm/configuration.nix#L44-L49) and [hetz86-1](https://github.com/tiiuae/ghaf-infra/blob/main/hosts/builders/hetz86-1/configuration.nix#L46-L51) builders).
- Start using `cachix-push.nix` in the release builders `hetz86-rel-1` and …
=> Initial version of cachix-push.nix

hosts/builders/cachix-push.nix, hosts/hetzci/auth.nix
Fix auth and cachix-push service restart rate limits, which did not work as explained in the earlier comments.
Also, fixes evaluation warnings from auth and cachix-push services, such as:
```
evaluation warning: Service 'oauth2-proxy.service' uses the attribute 'StartLimitInterval' in the Service section, which is deprecated. See https://github.com/NixOS/nixpkgs/issues/45786.
```
=> Fix cachix-push and auth service rate limits

hosts/ghaf-monitoring/configuration.nix, hosts/hetzner-cloud.nix, hosts/machines.nix, pkgs/sshified/default.nix
release builders were mistakenly set to be monitored through ssh instead of using hetzner internal network. The `hetzner-cloud.nix` module defaults to sending logs through internal ip. Added a nix evaluation warning to catch this in the future.
Also fixes sshified service as it was not using the binary from path properly.
=> Fix monitoring of release builders

hosts/azure-common.nix, hosts/builders/hetz86-rel-1/configuration.nix, hosts/builders/hetzarm-rel-1/configuration.nix, hosts/hetzci/common.nix, hosts/zramswap.nix
Move zramSwap configuration to separate module and start using the module on hosts that enable zramSwap.
This also increases the default memoryPercent to 150% which works fine in testing (ref: https://github.com/NixOS/nixpkgs/issues/103106)
=> Move zramswap configuration to nix module

flake.lock, hosts/hetzci/vm/casc/pipelines/ghaf-nightly.groovy
- Update ci-yubi input to include changes from https://github.com/tiiuae/ci-yubi/pull/29
- Copy the recent `prod` nightly pipeline changes to `vm`
Tested in `vm` by running the nightly pipeline and confirming the `uefisign` now works on x1 and darp11 targets.
=> Update ci-yubi flake input

flake.lock, flake.nix, hosts/hetzci/dev/casc/pipelines/modules/utils.groovy, hosts/hetzci/prod/casc/pipelines/modules/utils.groovy, hosts/hetzci/release/casc/pipelines/modules/utils.groovy, hosts/hetzci/vm/casc/pipelines/modules/utils.groovy
Trial a fix for the provenance generation issue, an example [here](https://ci-prod.vedenemo.dev/job/ghaf-nightly/117/pipeline-overview/?selected-node=593).
This PR includes two fixes:
- Use build out-path (instead of flake reference) as the provenance target. This should ensure the target is not re-evaluated, to make sure the provenance target is the same as the build output.
- Include a fix to provenance tool from the [sbomnix/fix-provenance](https://github.com/tiiuae/sbomnix/compare/main...fix-provenance) branch, which ensures the provenance subject is force-realised making sure the provenance target is always available in local nix store.
The issue is hard to reproduce, which is why I propose we merge and deploy this change, then monitor if we still see the issue. We could conclude the …
=> Trial provenance fix

hosts/hetzci/dev/casc/pipelines/ghaf-main.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly-poweroff.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-pre-merge-manual.groovy, hosts/hetzci/dev/casc/pipelines/ghaf-pre-merge.groovy, hosts/hetzci/dev/casc/pipelines/modules/utils.groovy, hosts/hetzci/jenkins.nix, hosts/hetzci/prod/casc/pipelines/ghaf-main.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-pre-merge-manual.groovy, hosts/hetzci/prod/casc/pipelines/ghaf-pre-merge.groovy, hosts/hetzci/prod/casc/pipelines/modules/utils.groovy, hosts/hetzci/purge-jenkins-artifacts.sh, hosts/hetzci/release/casc/pipelines/ghaf-release.groovy, hosts/hetzci/release/casc/pipelines/modules/utils.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-main.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-manual.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly-perftest.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly-poweroff.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-nightly.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-pre-merge-manual.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-pre-merge.groovy, hosts/hetzci/vm/casc/pipelines/ghaf-release.groovy, hosts/hetzci/vm/casc/pipelines/modules/utils.groovy
- Revert the [change](https://github.com/tiiuae/ghaf-infra/commit/4a37d6c796988173b9c2d89ab9a7afc4b98c907e) that reduced the number of builds as outlined in [PR#635](https://github.com/tiiuae/ghaf-infra/pull/635)
- Change `purge-jenkins-artifacts.sh`:
- Make it run once a minute
- Do nothing if nix store disk is less than 90% full
- Otherwise, remove old artifacts keeping only the artifacts from latest 3 builds on each pipeline to free-up disk space for nix GC.
Tested locally in a `vm` environment. Also, deployed to [`dev`](https://ci-dev.vedenemo.dev/).
=> Keep more jenkins logs
